### ISSUE TITLE
flips assertion failure

### ISSUE THREAD

**Issue by jdongca2003** [suragnair/alpha-zero-general#10]
Hi Surag,
    Thank for sharing good software.  When I ran it under tensorflow framework, I got the flips assertion failure.

------ITER 19------
Self Play |######################          | (71/100) Eps Time: 1.669s | Total: 0:01:58 | ETA: 0:00:51Traceback (most recent call last):
  File "main.py", line 30, in <module>
    c.learn()
  File "/home/***/tools/alpha-zero-general/Coach.py", line 78, in learn
    trainExamples += self.executeEpisode()                
  File "/home/***/tools/alpha-zero-general/Coach.py", line 46, in executeEpisode
    pi = self.mcts.getActionProb(canonicalBoard, temp=temp)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 31, in getActionProb
    self.search(canonicalBoard)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 106, in search
    v = self.search(next_s)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 106, in search
    v = self.search(next_s)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 106, in search
    v = self.search(next_s)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 106, in search
    v = self.search(next_s)
  File "/home/***/tools/alpha-zero-general/MCTS.py", line 103, in search
    next_s, next_player = self.game.getNextState(canonicalBoard, 1, a)
  File "/home/***/tools/alpha-zero-general/othello/OthelloGame.py", line 34, in getNextState
    b.execute_move(move, player)
  File "/home/***/tools/alpha-zero-general/othello/OthelloLogic.py", line 111, in execute_move
    assert len(list(flips))>0
AssertionError

System info:
   tensorflow-gpu 1.1.0
   master branch (head of commit:
"
   commit 263eccb2de3ca5eae7d5615e8b5b7d13b481b569
Author: suragnair <suragnair@hotmail.com>
Date:   Wed Jan 3 12:05:11 2018 +0530

    added dim to pytorch log_softmax (UserWarning)" )

  
I wonder whether it is possible that flips can be empty

Thanks

Jianxiong

**Comment by suragnair** [comment]
Hi Jianxiong

This is probably a corner case with the game logic. For now I suggest you change the random seed and continue training from the last checkpoint. Will try to solve this ASAP.

@ShantanuThakoor @jjw-megha

**Comment by jdongca2003** [comment]
Thanks Surag. I will follow your suggestion and try again.

**Comment by brianprichardson** [comment]
@suragnair I have encountered numerous assert exceptions under TF.  Would you like me to open issues for them here?  Just restarting seems to work fine, BTW.

**Comment by suragnair** [comment]
@brianprichardson are they of the same nature- `len(list(flip)` assertion?

**Comment by brianprichardson** [comment]
Yes, the most recent one was that problem.  If there are others that are different I'll post them separately.

**Comment by suragnair** [comment]
@jdongca2003 @brianprichardson have you been having these issues since the latest commits?

**Comment by brianprichardson** [comment]
I'll do an extended run this weekend as there have been many new commits.

**Comment by jdongca2003** [comment]
Hi, Surg, after you fixed tensorflow load bug, I re-ran it under TF.  206 iterations passed.  I did not observe any 'assert' and 'warning' message in the log file

check: cat nohup.out|grep assert
            cat nohup.out|grep Warning

some log message round 200 iteration:

ACCEPTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 27/13 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 35/5 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 19/21 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 19/21 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 27/13 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 20/20 ; DRAWS : 0
REJECTING NEW MODEL

**Comment by brianprichardson** [comment]
It ran for about a day without any flip type errors.  It did run out of GPU memory after the 14th checkpoint, which of course, is quite different.  Trying another run with GPU memory limits (Othello game with TF under Keras NN)
