### ISSUE TITLE
Exit code 1073741571 (0xC00000FD)

### ISSUE THREAD

**Issue by Zvikush90** [suragnair/alpha-zero-general#101]
Hi,

I am attempting to run othello training. I am getting the following error:

`
Process finished with exit code -1073741571 (0xC00000FD)
`
This happens approximately after 8 steps of the Coach.py while loop.
I saw online that it was recommended to do the following to increase stack and recursion:

```
import sys
import threading
sys.setrecursionlimit(1000000000)
threading.stack_size(200000000)
```

It increases for a few more steps but still crashes.

Thanks.

**Comment by Zvikush90** [comment]
I just added to the while loop a call to `gc.collect()`  from the garbage collection library by importing `import gc` and saw some improvement but crashes again after a few iterations. Any suggestions?

**Comment by suragnair** [comment]
Can you have a look at #23, #27 and #36 and see if it’s related?
