### ISSUE TITLE
Error in writeup

### ISSUE THREAD

**Issue by MerceaOtniel** [suragnair/alpha-zero-general#104]
Hello,

I was reading the write-up and the description of the loss on the website provided in the description. In the write-up you use  l = (z − v)2 + π log p + c||θ||2, but on the website and in the paper provided by deepmind they use  l = (z − v)2 − π log p + c||θ||2. I think using + is not ok as cross-entropy loss is defined with -. Am i right?

**Comment by suragnair** [comment]
Yep, you are correct.
