### ISSUE TITLE
I don't get it

### ISSUE THREAD

**Issue by aletote** [suragnair/alpha-zero-general#109]
Could anyone explain me why do I need to lower the size of the fully connected layers when I increase the size of the board, shouldn't be the same? Not to mention it is counterproductive.

**Comment by aletote** [comment]
Anyway, I used the ResNet class and now I don't run OOM. But I'm getting ValueError: Can't play column 7 on board [[-0. -0. -0. ... -0. -0. -0.] That column number changes everytime I run main.py

**Comment by gigayaya** [comment]
Your game change board size every times? What's your game?
