### ISSUE TITLE
MEMORY LEAKS

### ISSUE THREAD

**Issue by MerceaOtniel** [suragnair/alpha-zero-general#111]
Hello,

I was playing with this repository and i can see that there are apparently some memory leaks. I cannot figure it out, but even if i use numItersForTrainExamplesHistory=1( to keep only the current iteration example), the RAM(on the pc, not on the GPU) is going up every iteration, while my number of train examples is the same.I tried to figure it out, but i cannot find the problem. Anyone has any idea?

**Comment by threedliteguy** [comment]
I get 
  File "/home/user/git/alpha-zero-general/MCTS.py", line 117, in search
    v = self.search(next_s)
(just under 1000 lines of above, then...)
RecursionError: maximum recursion depth exceeded in comparison
after some time in pytorch and sooner in keras/tf, when using an actionsize of 2401. Not sure if related.

**Comment by evg-tyurin** [comment]
I suppose your game implementation does not detect the end of the game correctly either your game can last 1000 half-moves and more.

**Comment by threedliteguy** [comment]
Yes, you are right, it could last that long with random play. I will just declare a draw after so many moves then.
    On Wednesday, April 10, 2019, 1:37:41 AM CDT, Evgeny <notifications@github.com> wrote:  
 
 
I suppose your game implementation does not detect the end of the game correctly either your game can last 1000 half-moves and more.
