### ISSUE TITLE
How to choose framework

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#12]
from othello.keras.NNet import NNetWrapper as nn <----------------keras instead of pytorch

Is this not choosing the framework in main.py per the readme, or am I missing something ?
Thanks,
Brian

**Comment by suragnair** [comment]
Yes that’s exactly it. Is there an issue?

**Comment by brianprichardson** [comment]
Well, it works for pytorch and tensorflow, but not keras.

**Comment by suragnair** [comment]
What’s the error when you try keras?

**Comment by brianprichardson** [comment]
Checkpoint Directory does not exist! Making directory ./tempkeras/ Traceback (most recent call last): File "mainkeras.py", line 29, in <module> c.learn() File "/home/brian/alpha-zero-general/bin/alpha-zero-general/Coach.py", line 91, in learn pnet.load_checkpoint(folder=self.args.checkpoint, filename='temp.pth.tar') File "/home/brian/alpha-zero-general/bin/alpha-zero-general/othello/keras/NNet.py", line 70, in load_checkpoint raise("No model in path {}".format(filepath)) TypeError: exceptions must derive from BaseException (alpha-zero-general)

**Comment by suragnair** [comment]
Looks like #6 . Please ensure you’re on the latest commit.
