### ISSUE TITLE
invalid value in division

### ISSUE THREAD

**Issue by jdongca2003** [suragnair/alpha-zero-general#13]
When I ran 'main.py' under tensorflow, I also got runtime warning:

'.../othello/tensorflow/NNet.py: 103 RuntimeWarning: invalid value encountered in divide

 pi = np.exp(pi) / np.sum(np.exp(pi))
"

Here we calculated softmax. When one value in pi is large, the denominator may overflow.  

we can try the following method to avoid it.

x = np.exp(pi - np.max(pi))
pi = x/x.sum()

But not sure whether the above warning was caused by overflow.

Jianxiong

**Comment by suragnair** [comment]
Does that solve the issue?

**Comment by jdongca2003** [comment]
The program is running. Probably I can give you the answer tomorrow.

By the way, I also observed that the similar warning ("RuntimeWarning: invalid value encountered in divide") occurred here

MCTS.py : line 80 "self.Ps[s] /= np.sum(self.Ps[s])    # renormalize"

**Comment by suragnair** [comment]
Could you print the output of the neural network that is giving the warning?

**Comment by jdongca2003** [comment]
I checked the log this morning:

The program passed 47 iterations and still ran.  I did not observe warning at /othello/tensorflow/NNet.py: 103 when the above method was applied.  Only a warning occurred at  "MCTS.py:80: RuntimeWarning: invalid value encountered in divide".

some log outputs at iteration 48:
"
EPOCH ::: 1
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.4575 | Loss_v: 0.358
EPOCH ::: 2
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.4226 | Loss_v: 0.348
EPOCH ::: 3
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3957 | Loss_v: 0.342
"
It seems to be normal.

>Could you print the output of the neural network that is giving the warning?
I will try to print 'Ps after MCTS.py: line 80' in another round when the current training ends.

**Comment by jdongca2003** [comment]
The program still exited with assertion failure at iteration 64
"othello/OthelloLogic.py line 111  assert len(list(flips)) > 0"

(Note: in the last run, without update tensorflow/NNet.py: 103, it exited with the same assertion failure at iteration 18.

For pytorch, you can pass 80 iterations.  Is it possible that the issue also exists under pytorch?)

some log outputs from iteration 64:

Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3299 | Loss_v: 0.293
EPOCH ::: 8
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3281 | Loss_v: 0.294
EPOCH ::: 9
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3304 | Loss_v: 0.293
EPOCH ::: 10
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3297 | Loss_v: 0.291

**Comment by jdongca2003** [comment]
> MCTS.py : line 80 "self.Ps[s] /= np.sum(self.Ps[s]) # renormalize"
I changed the above statement to the following lines:
"
           t = np.sum(self.Ps[s])
            if not np.isclose(t, 0):
                self.Ps[s] /= t    # renormalize
            else:
                print("t is too small")
                print(t)
                print(self.Ps[s])
"
Here I did not renormalize Ps[s] when sum is very small.  It may break the logic. Probably we can add a little random noise and renormalize Ps[s]. Here you can see some logs:

t is too small
4.03304989405e-09
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   4.03304989e-09]
t is too small
1.15952983326e-10
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   1.15952983e-10]

**Comment by jdongca2003** [comment]
Hi, Surag,
     I did 3 changes:
1) othello/tensorflow/NNet.py: 103. Replace the original softmax by
    x = np.exp(pi - np.max(pi))
    pi = x/x.sum()
2) othello/OthelloLogic.py: 111  comment out "assert len(list(flips))>0"
3) MCTS.py : line 80 "self.Ps[s] /= np.sum(self.Ps[s]) # renormalize", Replace it by
   t = np.sum(self.Ps[s])
   if not np.isclose(t, 0):
      self.Ps[s] /= t # renormalize
  else:
     print("t is too small")
     print(t)
     print(self.Ps[s]) 
I did not observe any warning. The program passed 146 iterations. Then I manually stopped it and run 'python pit.py'.  The agent behavior seems to be ok.
(Note: in order run pit.py, I need to replace "othello/OthelloPlayers.py line 24: a = input()" to "a = raw_input()" )

Some logs from iteration 146:
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3335 | Loss_v: 0.344
EPOCH ::: 9
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3350 | Loss_v: 0.343
EPOCH ::: 10
Training Net |################################| (3125/3125) Data: 0.000s | Batch: 0.026s | Total: 0:01:21 | ETA: 0:00:01 | Loss_pi: 0.3420 | Loss_v: 0.347
PITTING AGAINST PREVIOUS VERSION
t is too small
1.27786132692e-15
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   1.27786133e-15]

Jianxiong

**Comment by suragnair** [comment]
Hi Jianxiong

Thanks for the observations. I do not quite understand why the neural network is returning such small values for the last action (which is 'PASS'). Any clues?

Could you display the state of the board for the same (i.e. display s if t is too small).

**Comment by jdongca2003** [comment]
I have not figured out the root cause yet.  Ps[s] is logits (size of action space is 6 * 6  + 1).
6 * 6 corresponds to the size of the board. What is the extra 1?

Based on the observed outputs, it seems that all actions have equal probability. In this case, choosing any one may be ok.

t is too small
7.47570005899e-09
[[-1, -1, -1, -1, -1, -1], [-1, -1, -1, 1, -1, -1], [-1, -1, 1, 1, 1, -1], [-1, 0, -1, -1, -1, -1], [-1, -1, 1, -1, 1, -1], [-1, 0, 1, 1, 1, 1]]
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   7.47570006e-09]
t is too small
8.25224688583e-09
[[-1, -1, -1, -1, -1, -1], [1, -1, -1, 1, -1, -1], [1, 1, 1, 1, 1, -1], [0, 0, -1, -1, -1, -1], [1, -1, 1, -1, 1, -1], [-1, 0, 1, 1, 1, 1]]
[  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   8.25224689e-09   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00]

**Comment by jdongca2003** [comment]
Hi, Surag,
     The small values is due to valids, which masks the invalid actions.

After masking, sum of self.Ps[s]: t is too small
2.48407383552e-09

s: [[-1, -1, -1, -1, 1, 0], [-1, -1, -1, -1, -1, -1], [-1, -1, 1, -1, -1, -1], [-1, 1, -1, -1, -1, -1], [1, -1, 1, -1, 1, -1], [-1, -1, -1, 0, 0, -1]]
After masking self.Ps[s]: [  0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   0.00000000e+00   0.00000000e+00   0.00000000e+00   0.00000000e+00
   2.48407384e-09]
Without masking, self.Ps[s]: [  4.02341299e-10   2.51677221e-08   2.53018734e-11   1.01719775e-06
   8.08362245e-07   1.33664664e-02   1.04710199e-11   1.36595709e-15
   8.02129901e-14   5.27473620e-09   1.14397864e-07   4.41102969e-07
   3.18400524e-08   5.06576482e-15   1.61438422e-24   3.04578388e-22
   5.03612430e-10   7.17689588e-08   4.23766466e-10   7.77312416e-12
   2.06206466e-25   1.60347843e-23   3.52946472e-08   5.81096016e-09
   4.25181845e-09   4.05102445e-11   5.32517697e-10   6.49298185e-11
   8.65622418e-09   3.24868550e-13   1.45046144e-07   9.62232662e-07
   1.31823413e-07   9.72581387e-01   1.40482914e-02   2.15384460e-10
   2.48407384e-09]

Jianxiong

**Comment by suragnair** [comment]
The extra 1 in the 37 actions is the 'PASS' move. 

Thanks for the above observation. Do you observe this more during the initial stages of learning compared to the later stages?

**Comment by jdongca2003** [comment]
not necessary. I observed that most iterations have 1 or 2 small value after masking.

**Comment by suragnair** [comment]
This is very unexpected. This means that it isn't learning the rules of the game even after the first few iterations- this is not the expected behavior (and the division warnings are not observed when using PyTorch). I also received a mail that mentioned that the tensorflow model does not improve over iterations.

This error might be in the `load_checkpoint` and `save_checkpoint` methods in [NNet.py](https://github.com/suragnair/alpha-zero-general/blob/master/othello/tensorflow/NNet.py). Any ideas?

**Comment by jdongca2003** [comment]
It seemed  that it was learning the rules under tf. Several observations:
1) check Loss_pi and Loss_v across different iterations.  Pi_loss is decreasing 
  e.g. 
Epoch 10 Iter: 1 Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 0.9987 | Loss_v: 0.241
Epoch 10 Iter: 2 Training Net |################################| (811/811) Data: 0.000s | Batch: 0.031s | Total: 0:00:25 | ETA: 0:00:01 | Loss_pi: 0.7371 | Loss_v: 0.203
Epoch 10 Iter: 3 Training Net |################################| (1219/1219) Data: 0.000s | Batch: 0.031s | Total: 0:00:38 | ETA: 0:00:01 | Loss_pi: 0.6632 | Loss_v: 0.200
Epoch 10 Iter: 4 Training Net |################################| (1629/1629) Data: 0.000s | Batch: 0.031s | Total: 0:00:50 | ETA: 0:00:01 | Loss_pi: 0.6215 | Loss_v: 0.208
Epoch 10 Iter: 5 Training Net |################################| (2040/2040) Data: 0.000s | Batch: 0.031s | Total: 0:01:04 | ETA: 0:00:01 | Loss_pi: 0.5936 | Loss_v: 0.212
Epoch 10 Iter: 6 Training Net |################################| (2449/2449) Data: 0.000s | Batch: 0.032s | Total: 0:01:17 | ETA: 0:00:01 | Loss_pi: 0.5756 | Loss_v: 0.217
Epoch 10 Iter: 7 Training Net |################################| (2857/2857) Data: 0.000s | Batch: 0.032s | Total: 0:01:30 | ETA: 0:00:01 | Loss_pi: 0.5587 | Loss_v: 0.219
Epoch 10 Iter: 8 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.5326 | Loss_v: 0.226
Epoch 10 Iter: 9 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4937 | Loss_v: 0.237
Epoch 10 Iter: 10 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:39 | ETA: 0:00:01 | Loss_pi: 0.4725 | Loss_v: 0.240
Epoch 10 Iter: 11 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4602 | Loss_v: 0.250
Epoch 10 Iter: 12 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4509 | Loss_v: 0.256
Epoch 10 Iter: 13 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4398 | Loss_v: 0.259
Epoch 10 Iter: 14 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:39 | ETA: 0:00:01 | Loss_pi: 0.4309 | Loss_v: 0.265
Epoch 10 Iter: 15 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4257 | Loss_v: 0.277
Epoch 10 Iter: 16 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4185 | Loss_v: 0.279
Epoch 10 Iter: 17 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4159 | Loss_v: 0.282
Epoch 10 Iter: 18 Training Net |################################| (3125/3125) Data: 0.001s | Batch: 0.032s | Total: 0:01:38 | ETA: 0:00:01 | Loss_pi: 0.4061 | Loss_v: 0.282

2) New/prev wins
NEW/PREV WINS : 31/9
NEW/PREV WINS : 38/2
NEW/PREV WINS : 38/2
NEW/PREV WINS : 38/2
NEW/PREV WINS : 36/4
NEW/PREV WINS : 38/2
NEW/PREV WINS : 37/3
NEW/PREV WINS : 39/1
NEW/PREV WINS : 40/0
NEW/PREV WINS : 36/4
NEW/PREV WINS : 37/3
NEW/PREV WINS : 37/3
NEW/PREV WINS : 38/2
NEW/PREV WINS : 39/1
NEW/PREV WINS : 39/1
NEW/PREV WINS : 39/1
NEW/PREV WINS : 40/0
NEW/PREV WINS : 40/0

3) tensorflow was updating the model directory './temp'
   116838864 Jan 11 14:56 checkpoint_18.pth.tar.data-00000-of-00001
   checkpoint_18.pth.tar.index
  checkpoint_18.pth.tar.meta

**Comment by jdongca2003** [comment]
see iteration 1 (both loss_pi and loss_v are decreasing)

Iter: 1, Epoch: 1  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.032s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 2.7545 | Loss_v: 1.080
Iter: 1, Epoch: 2  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 2.2580 | Loss_v: 0.774
Iter: 1, Epoch: 3  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.7358 | Loss_v: 0.682
Iter: 1, Epoch: 4  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.5307 | Loss_v: 0.573
Iter: 1, Epoch: 5  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.4005 | Loss_v: 0.483
Iter: 1, Epoch: 6  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.2814 | Loss_v: 0.423
Iter: 1, Epoch: 7  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.1872 | Loss_v: 0.355
Iter: 1, Epoch: 8  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.1058 | Loss_v: 0.309
Iter: 1, Epoch: 9  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 1.0412 | Loss_v: 0.267
Iter: 1, Epoch: 10  Training Net |################################| (404/404) Data: 0.000s | Batch: 0.031s | Total: 0:00:12 | ETA: 0:00:01 | Loss_pi: 0.9987 | Loss_v: 0.241

**Comment by suragnair** [comment]
Thanks for the logs! There is certainly a bug somewhere. The `NEW/PREV WINS` ratio is typically very high for the first one or two iterations, but then reduces to typically 25/15 or so (when using PyTorch or Keras), which is not the case now. I suspect the scopes are not being handled correctly in TensorFlow.

**Comment by suragnair** [comment]
So it turns out that when using TensorFlow, load_checkpoint is not working correctly here.

https://github.com/suragnair/alpha-zero-general/blob/7cd0305d525f9e43f38d6317ed4a865c01e3c0f1/Coach.py#L91

The model is initialised to a random model. Any idea why it's happening?

**Comment by suragnair** [comment]
So it turns out that when using TensorFlow, `load_checkpoint` was not working correctly here.

I've fixed it with the latest commit. Can you pull it and let me know if you're still observing the numerical errors? Also, please report the `NEW/PREV WINS` ratio. Thanks!

**Comment by jdongca2003** [comment]
I checked out your code and re-ran it under tf (13 iterations):

NEW/PREV WINS : 33/7 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 31/9 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 20/20 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 10/30 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 31/9 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL

**Comment by suragnair** [comment]
Are you seeing the numerical issues anymore? Before the above correction, were you facing them mostly in the Arena stage when the new and old players were being pit against each other?

**Comment by jdongca2003** [comment]
After 39 iterations passed, I did not observe numerical issues. 
> Before the above correction, were you facing them mostly in the Arena stage when the new and old players were being pit against each other?
Yes

PIT logs for 39 iterations:

NEW/PREV WINS : 33/7 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 31/9 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 20/20 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 10/30 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 31/9 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 25/15 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 26/14 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 19/21 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 22/18 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 25/15 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 26/14 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 26/14 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 19/21 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 25/15 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 29/11 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 26/14 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 23/17 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 27/13 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 26/14 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 13/27 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 14/26 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 28/12 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 27/13 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 17/23 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 27/13 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 21/19 ; DRAWS : 0
REJECTING NEW MODEL
NEW/PREV WINS : 31/9 ; DRAWS : 0
ACCEPTING NEW MODEL
NEW/PREV WINS : 35/5 ; DRAWS : 0
ACCEPTING NEW MODEL

**Comment by suragnair** [comment]
Thanks for your help Jianxiong. The error was due to incorrect loading of checkpoint in TensorFlow, which caused the agent to be pit against a randomly initialised opponent every iteration.
