### ISSUE TITLE
AssertionError on a game (Conhex) implementation

### ISSUE THREAD

**Issue by Aemaeth60** [suragnair/alpha-zero-general#135]
Hello,

We are two French students who were asked to work on an implementation of an IA based on neural networks (you can read the rules here : https://nestorgames.com/rulebooks)./CONHEX_EN.pdf
As a starting point, one of our teachers told us about your code. Of course, we didn't hesitate too much before choosing to use it, because it is clearly some good work :).
After implementing Conhex Game (with lot of errors) we got to the point where there's still an error.
Indeed, when we try to do a training we quickly get an AssertionError: 
```
Traceback (most recent call last):
File "main.py", line 34, in <module>
    c.learn()
  File "/home1/imc01/Conhex/Coach.py", line 85, in learn
    iterationTrainExamples += self.executeEpisode()
  File "/home1/imc01/Conhex/Coach.py", line 56, in executeEpisode
    board, self.curPlayer = self.game.getNextState(board, self.curPlayer, action)
  File "/home1/imc01/Conhex/conhex/ConHexGame.py", line 40, in getNextState
    b.execute_move(move, player)
  File "/home1/imc01/Conhex/conhex/ConhexLogic.py", line 124, in execute_move
    raise AssertionError()
AssertionError

```
After printing the board, we discovered that an action is performed on an already "possessed node" of our board.

Is it possible to have some help about this?
Thanks in advance.

PS: Sorry for the bad english and the bad programming skill (we're still learning ahah)

You can find the code here : https://github.com/Aemaeth60/Conhex (it is a copy of your repo)

**Comment by suragnair** [comment]
Hi, thanks for trying the repo. The assertion error you are getting has to do with the Conhex game logic. Unfortunately I don't really know the game so I can't help with that. It would be useful to try to understand the case where the assertion error is triggered.

**Comment by Aemaeth60** [comment]
Thanks for your consideration. 

Our professor told us the same thing. The fact is that we launched about 20k games between two random players and we didn't get any AssertionError. Does it mean something or nothing at all?

In any case, we'll keep working on it.

**Comment by suragnair** [comment]
If the assertion error is reproducible, it may be helpful to see what move triggers it. Try to add some print statements/use a debugger to see what causes the error. It may be the case that there is an error in the alpha zero code since the bug is not showing up when you pit random players against each other.

**Comment by Aemaeth60** [comment]
Yes, we did some debugging things lol. I forgot to tell that the assertion error always happens at (0,0) coordinates.

**Comment by Aemaeth60** [comment]
AssertionError was due to some mistakes in getGameEnded function.
Thanks for your help.
