### ISSUE TITLE
implemention from alphago zero or alpha zero?

### ISSUE THREAD

**Issue by zfavourite99** [suragnair/alpha-zero-general#137]
excerpt from deepmind alpha zero paper:

In AlphaGo Zero, self-play games were generated by the best player from all previous iterations. After each iteration of training, the performance of the new player was measured against the best player; if the new player won by a margin of 55%, then it replaced the best player. By contrast, AlphaZero simply maintains a single neural network that is updated continually rather than waiting for an iteration to complete. Self-play games are always generated by using the latest parameters for this neural network.

but in Coach.py generate self-play games use best. this is alphago zero.

**Comment by 51616** [comment]
You can skip evaluation step in `Coach.py` to do continuous update like AlphaZero

**Comment by suragnair** [comment]
Same as #74
