### ISSUE TITLE
Cannot create container ''pytorch_notebook''

### ISSUE THREAD

**Issue by wang-zm18** [suragnair/alpha-zero-general#142]
My docker version is 19.03, when I run "setup_env.sh", it always occurs "docker: Error response from daemon: pull access denied for pytorch, repository does not exist or may require 'docker login': denied: requested access to the resource is denied."
 I tried "docker login", but it did not work.  When I run "docker run  hello-world" , it works well. So what should I do ?

**Comment by wang-zm18** [comment]
I found the key  issue is that I cannot build an image named "pytorch:0.4.0-py3-gpu" by the file "./docker/Dockerfile.pytorch".  When I ran "setup_env.sh"，the error is like the following picture:
![捕获](https://user-images.githubusercontent.com/47704679/66712220-e8b79480-edcb-11e9-85a2-5dfc7d85cf7a.PNG).  Is there anyone meeting with the same trouble?

**Comment by wang-zm18** [comment]
I found that pytorch0.4.0 is discarded. The only thing needs to be done is 
step  1：  set "PYTORCH_IMAGE=pytorch:0.4.1-py3-gpu" in “setup_env.sh” file
step  2:  set "pytorch=0.4.1" in "./docker/Dockerfile.pytorch" file.
After these modifications,  the code can run normally.

**Comment by suragnair** [comment]
Thanks for debugging this! Can you please make a pull request with the changes so I can modify them?

**Comment by suragnair** [comment]
Fixed in a1b230d6
