### ISSUE TITLE
In pit.py line 45, is it supposed to be n2.load_checkpoint()? I'm pretty confused.

### ISSUE THREAD

**Issue by Nyquixt** [suragnair/alpha-zero-general#144]
https://github.com/suragnair/alpha-zero-general/blob/bc8b17cdd3b742352e3f9af128e9741bd6badde1/pit.py#L45

**Comment by suragnair** [comment]
Looks like a bug in the latest push, @edwardtau can you please verify.

**Comment by edwardtau** [comment]
Yes, this is a bug.  I will fix.

**Comment by edwardtau** [comment]
Bug fix checked in (pull request #145).
