### ISSUE TITLE
Question about applying to different game

### ISSUE THREAD

**Issue by jameschang0125** [suragnair/alpha-zero-general#146]
I’m trying to apply alphazero general to different games (i.e. chess), but I’m not sure about some details:
1. Should num_channels be modified?
2. Should the “board” be a 3D or 2D array? For example, in othello, we use a 2D array to represent the board. However, in chess, there are more than one kind of pieces.
Thanks for any reply!

**Comment by evg-tyurin** [comment]
1. Should
2. 3D is more preferable for chess

You can watch my repo adopted for checkers - https://github.com/evg-tyurin/alpha-nagibator
It's based on idea and code of this repo with some changes including input stack of planes.

**Comment by jameschang0125** [comment]
Thanks! I’ll give it a try.

**Comment by jameschang0125** [comment]
um I would like to know (generally) what should I change for inputting a 3D array (or stack of planes, as @evg-tyurin evg-tyurin mentioned)

**Comment by evg-tyurin** [comment]
At least, a method which transforms board position into stack of planes and input layer of your neural network.
