### ISSUE TITLE
TicTacToe doesn't display any tactics.

### ISSUE THREAD

**Issue by goshawk22** [suragnair/alpha-zero-general#148]
After training a model of the TicTacToe game, I found that the model 'completed' the game after a couple of iterations, however did not display any of the usual techniques when it went first. It would play optimally when the human goes first, but when it went first, played like it was assuming that I was an optimal player and that there was no point in using these techniques because the game would be a draw whatever. Is there any way to resolve this issue, such as using training data against a random, or not optimal, player?

**Comment by goshawk22** [comment]
Once the params are changed around the model displays better tecnhique. I will try different configs and the make a PR with a new model.

**Comment by suragnair** [comment]
#156 may explain this phenomena

**Comment by goshawk22** [comment]
Yeah this seems to be the cause of some of the problems I have been having. Thanks for pointing it out!
