### ISSUE TITLE
Question about getValidMoves for 3D Board

### ISSUE THREAD

**Issue by goshawk22** [suragnair/alpha-zero-general#151]
I am currently writing game code for 3D TicTacToe, but am unsure how to write the getValidMoves function in Game.py?
The board has z,x and y dimensions.

**Comment by rlronan** [comment]
Assuming you're storing the board as a 3d array, and moves as triples (x,y,z) then

 def get_legal_moves(self, color):
        """Returns all the legal moves for the given color.
        (1 for white, -1 for black)
        @param color not used and came from previous version.        
        """
        moves = set()  # stores the legal moves.

        # Get all the empty squares (color==0)
        for y in range(self.n):
            for x in range(self.n):
                for z in range(self.n):
                    if self[x][y][z]==0:
                        newmove = (x,y,z)
                        moves.add(newmove)
        return list(moves)

**Comment by goshawk22** [comment]
Thank you, I think it's working now.
