### ISSUE TITLE
getGameEnded definition/usage incompatible with games where inability to move results in a loss

### ISSUE THREAD

**Issue by rlronan** [suragnair/alpha-zero-general#156]
The defintion + usage of getGameEnded makes it incompatible with games where inability to make a move on your turn results in a loss.
```
 def getGameEnded(self, board, player):
        """
        Input:
            board: current board
            player: current player (1 or -1)
        Returns:
            r: 0 if game has not ended. 1 if player won, -1 if player lost,
               small non-zero value for draw.
        """
```
(Although Othello is implemented with a different function specification: " return 0 if not ended, 1 if player 1 won, -1 if player 1 lost")

But the function playGame in Arena 
```
def playGame(self, verbose=False):
        """
        Executes one episode of a game.
        Returns:
            either
                winner: player who won the game (1 if player1, -1 if player2)
            or
                draw result returned from the game that is neither 1, -1, nor 0.
        """
```

returns self.game.getGameEnded(board, 1). 

In any game where the current player not having a valid move results in a loss, rather than a draw, or a pass, this is a problem. getGameEnded is specified to be current player dependent, but it isn't used that way in Arena. 
For example if the current player is player2, and that player loses because they have no moves, then playGame returns:
self.game.getGameEnded(board, 1) which may be a 0 instead of a 1, since player1 may still have moves, and so the 'current player' from the perspective of the return statement thinks no one lost. 
Or it may return -1, if player1 also has no legal moves, even though they won the game. 

I propose as a solution that line 58 of Arena.py is changed from:
`return self.game.getGameEnded(board, 1)`
to:
`return curPlayer*self.game.getGameEnded(board, curPlayer)`

This change is consistent with the current implementation. but also allows for games where the current player being unable to perform a move results in a loss for them:

Current player | Winning Player | New return value | Old return value | Old return value if curPlayer lost because they no moves
--------------- | --------------- | ----------------- | ----------------- | -----------------------------
-1                    |1                       |   -1*(-1) =1          |      1  |  -1, 0, or 1 depending on implementation
-1  |  -1  |  -1*(+1) = -1 |  -1  | N/a
1 | 1| 1*(1) =1 | 1 | N/a
1 | -1 | 1*(-1)=-1 | -1 | -1 (probably)

**Comment by suragnair** [comment]
Wow, good catch! This is a pretty subtle bug. I'm hazy on the details but it seems like `self.game.getGameEnded(board, 1)` evaluates the board assuming that player 1 is playing. This is definitely very problematic and can lead to the wrong labels for training. E.g. in tic-tac-toe I can see that you may get the wrong label if player -1 is about to win but the board is evaluated from the point of view of player 1.

Thanks very much again! This may explain some of the bugs people have previously observed for some games.
