### ISSUE TITLE
Speed up self play.

### ISSUE THREAD

**Issue by goshawk22** [suragnair/alpha-zero-general#162]
While simultaneous self play is not supported, is it possible to get the self play code to execute on the CPU? I found that self play executed quicker on my CPU than on my GPU, possibly because it has a higher clock.
Does a different version of tensorflow need to be imported or something else?

**Comment by rlronan** [comment]
In NNet.py, does changing line 31 to the following work:
`sess = tf.Session(graph=self.nnet.graph, config=tf.ConfigProto(device_count={'GPU': 0}))`

**Comment by dberma15** [comment]
Did this solve the problem?
