### ISSUE TITLE
input: possibilities instead of situation

### ISSUE THREAD

**Issue by keesdejong** [suragnair/alpha-zero-general#164]
I've come up with a method that works much faster than the solutions I see here. I see that with all implementations the current situation on the board is given as input. I imagine that the network always has to interpret that situation first, only then the real thinking begins.

I could not use this method because my game does not involve a board with fixed dimensions.
So I came up with something else. I simply skip the first step. I do not feed the network with the current situation on the board but I only give it the possible moves. In the case of legitimate moves, the fields of the person whose turn it is are assigned "1". His opponent's legitimate fields are marked "-1" and all other prohibited fields are marked "0".
I get significantly better results! And I can handle many more situations. An important advantage (for me) is that you can handle multiple board dimensions with 1 network.

I myself am a chess player and I see the same distinction between amateurs and professionals. When a professional looks at the board he sees possibilities, when an amateur looks he first sees wooden pieces and only somewhere in the distance does he see possibilities.  For that reason alone, he plays worse.

But I understand that this method is not suitable for every game, maybe not for chess and so on   However, I am sure that this method can be very beneficial for certain games. I suspect it is for Go with a few changes..

**Comment by goshawk22** [comment]
Interesting. Can you make a PR?

**Comment by rlronan** [comment]
What game are you training? 
How would this work a game like tic tac toe? E.g. how do you distinguish the following boards?

 _ | _ | _
-- | -- | ---
 x |  x  | o
 _ | _ | _

 _ | _ | _
-- | -- | ---
 x |  o  | x
 _ | _ | _

 _ | _ | _
-- | -- | ---
 o |  x  | x
 _ | _ | _

**Comment by goshawk22** [comment]
I will have a look into it. After all, now schools are closed I have plenty of time!!

**Comment by rlronan** [comment]
@goshawk22, well my point was with only the set of possible actions, those 3 board states are indistinguishable, since each player has legitimate moves in every cell in row 1, and 3. All of these states would like: 

 1/-1 | 1/-1 | 1/-1
-- | -- | ---
 0 |  0  | 0
 1/-1 | 1/-1 | 1/-1

If it's player o's turn, they can't tell whose pieces are where, and thus they can't tell where they should play.

**Comment by goshawk22** [comment]
@rlronan make sense. Thanks for explaining.

**Comment by keesdejong** [comment]
@goshawk22: I could make a PR, but I have already made so many deviations from the original that it does not seem useful to me.

**Comment by keesdejong** [comment]
Maybe I should clarify my idea a bit. It does not necessarily work on every game. But in my game very well. It could also work well with the 8-Queen problem, for example.
Suppose you put 1 queen on the board, then that move mainly has consequences for the number of possibilities on other fields. The placed queen herself is not very interesting. With the 8-queen problem, you do not give that one queen as input to the network, but the possibilities on the other fields.

It is different in a game like GO. A placed stone at GO always has a certain influence that is important.

You must therefore determine per game whether you can make that distinction. I think stones placed with tic tac have an influence, so this game does not seem to me to be suitable for this method.

**Comment by keesdejong** [comment]
@rlronan
I mentioned the numbers "1", "-1" and "0" for illustrative purposes only. In the game I am working on myself I need many more possibilities. For that reason I extended the input with an extra dimension. There are branches here with examples of how to do that.
Warning: you do need some extra from the computer you use. All glues on my laptop broke down.
