### ISSUE TITLE
Fix for biased best action choice in MCTS

### ISSUE THREAD

**Issue by rlronan** [suragnair/alpha-zero-general#166]
The choice of best action is weighted towards actions with an earlier index (in pi). Instead of taking the argmax(counts) to get the best action, we should pick randomly between all actions which have value of max(counts).
see #165 

Since counts is an integer, taking bestA = np.argmax(counts) always weights our action choice towards earlier entries (in the list of actions) when multiple (s,a) pairs have the same maximum count. We should pick randomly from the set of actions with maximum counts. I have provided a pull, but I don't know if that is the optimal implementation.

**Comment by suragnair** [comment]
Agreed, merged. Thanks!
