### ISSUE TITLE
connect4

### ISSUE THREAD

**Issue by gms2009** [suragnair/alpha-zero-general#167]
not sure how it is coming, delete it or close it

**Comment by gms2009** [comment]
put something interesting(I think) out so it does not look so stupid

in some situation, neither players have valid move although there still empty spots on the board, will that put issue # 156 into a dead loop

(;GM[2]FF[4]
CA[UTF-8]
AP[Quarry:0.2.0]
SZ[8]
RE[W+59]
;B[cd];W[ec];B[fc];W[ce];B[dc];W[bd];B[ef];W[fe];B[df];W[fd]
;B[ff];W[cb];B[bf];W[cc];B[ca];W[cf];B[ae];W[af];B[cg];W[ad]
;B[ac];W[ab];B[bc];W[be];B[db];W[ag];B[bg];W[bh];B[dg];W[dh]
;B[ch];W[ah];B[eh];W[ea];B[da];W[ba];B[bb];W[aa];B[eb];W[eg]
;B[fg];W[fh];W[fa];B[fb];W[gh];W[gg];W[ge];B[gf];W[hg];W[gd]
;B[gc];W[hc];B[hd];W[he];W[gb]
)

**Comment by rlronan** [comment]
Sorry I can't quite follow the format of game state. Can you elaborate on how to read:
(;GM[2]FF[4]
CA[UTF-8]
AP[Quarry:0.2.0]
SZ[8]
RE[W+59]
;B[cd];W[ec];B[fc];W[ce];B[dc];W[bd];B[ef];W[fe];B[df];W[fd]
;B[ff];W[cb];B[bf];W[cc];B[ca];W[cf];B[ae];W[af];B[cg];W[ad]
;B[ac];W[ab];B[bc];W[be];B[db];W[ag];B[bg];W[bh];B[dg];W[dh]
;B[ch];W[ah];B[eh];W[ea];B[da];W[ba];B[bb];W[aa];B[eb];W[eg]
;B[fg];W[fh];W[fa];B[fb];W[gh];W[gg];W[ge];B[gf];W[hg];W[gd]
;B[gc];W[hc];B[hd];W[he];W[gb]
)

**Comment by gms2009** [comment]
this is othello 8x8 game, use quarry in fedora will open it, or you can use othello 8x8 gui to play it

**Comment by rlronan** [comment]
> in some situation, neither players have valid move although there still empty spots on the board, will that put issue # 156 into a dead loop

No, it will not. Not unless black and white have no moves and the same number of pieces. 
In the game you posted: Black is player 1, white player -1. After white makes that last move, it becomes black's turn.
[getGameEnded(board, player)](https://github.com/suragnair/alpha-zero-general/blob/28331bbc48d96c2fecd0683266f76d92ca33c62d/othello/OthelloGame.py#L59) runs:
Neither player has legal moves, and black doesn't have more pieces than white, so the function returns -1. As per the fix  ( #157 )  to #156, the game returns:
        `curPlayer*self.game.getGameEnded(board, curPlayer)`
which is : `1*-1`, which correctly indicates that player -1 (player 2) won.
