### ISSUE TITLE
Changing `cpuct` doesn't seem to have an effect

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#169]
I think `cpuct` is not being utilized. There's no comment in `main.py` so my guess is that this is "CPU count" for parallelization. I tried many values for this between 1 and 12 and it had no changes on my CPU utilization.

**Comment by suragnair** [comment]
It's actually not a CPU count parameter, rather it's a hyperparameter that controls the degree of exploration. 

https://github.com/suragnair/alpha-zero-general/blob/28331bbc48d96c2fecd0683266f76d92ca33c62d/MCTS.py#L106

**Comment by mikhail** [comment]
Can main.py be updated to explain how to configure it? Other values have good comments
