### ISSUE TITLE
stringRepresentation is not readable when printing

### ISSUE THREAD

**Issue by jdongca2003** [suragnair/alpha-zero-general#17]
Hi, Surg,
     In https://github.com/suragnair/alpha-zero-general/blob/master/othello/OthelloGame.py: line 85  under function stringRepresentation.

def stringRepresentation(self, board):
    	# 8x8 numpy array (canonical board)
    	return board.tostring()

When you try to print the returned string, it shows "@@@".  It is not good for debugging.

We can do it in the following:
import json

def stringRepresentation(self, board):
      return json.dumps(board.tolist())

e.g.
import numpy as np
import json
a = np.array([[2.0, 3.0], [4.0, 5.0]))
print(a.tostring())
 @@@
print(json.dumps(a.tolist()))
  [[2.0, 3.0], [4.0, 5.0]]

Probably tostring is more efficient but losing readability.

Thanks

Jianxiong

**Comment by suragnair** [comment]
Hi Jianxiong

The `stringRepresentation` method is for converting the board to a key for efficient hashing. You can use the `display` method for debugging.

**Comment by jdongca2003** [comment]
Good point. You can close it.
