### ISSUE TITLE
Eliminate bottleneck in `stringRepresentation` [SPEED IMPROVEMENT]

### ISSUE THREAD

**Issue by manuelsh** [suragnair/alpha-zero-general#172]
I time profiled the code, and this line becomes a bottleneck, because of the string.

https://github.com/suragnair/alpha-zero-general/blob/28331bbc48d96c2fecd0683266f76d92ca33c62d/connect4/Connect4Game.py#L63

```
    def stringRepresentation(self, board):
        return str(self._base_board.with_np_pieces(np_pieces=board))
```

Another issue is that sometimes returns '-0.' instead of just '0'.

My suggestion: substitute it by something 100 times faster, although not so readable:
```
    def stringRepresentation(self, board):
         return board.astype(int).tostring()
```
is true that we are not running the `assert` contained in `Board.__init__` when we run `.with_np_pieces`, but on the other hand, running it in all iterations, may be too much.

**Comment by NMO13** [comment]
I basically agree. But why would you need ```astype(int)```?
How about this?
```
    def stringRepresentation(self, board):
         return board.tostring()
```

> Another issue is that sometimes returns '-0.' instead of just '0'.
That also true. This leads to two different states although it should not. I solved it by simply adding +1
```

    def getCanonicalForm(self, board, player):
        # +0 replace -0 with 0
        # see https://stackoverflow.com/questions/11010683/how-to-have-negative-zero-always-formatted-as-positive-zero-in-a-python-string
        return board * player + 0
```

**Comment by manuelsh** [comment]
oh if you convert to ´int´ then you solve the issue of the -0. and 0. treated as different states. You solved that already? In the latest version I used I still saw the -0.

btw, congratulations for the implementation.

**Comment by NMO13** [comment]
> oh if you convert to ´int´ then you solve the issue of the -0. and 0. treated as different states. 

But I think
`board.tostring()` and `board.astype(int).tostring()` yields the same result. 
My implementation was just a suggestion but if it is faster using bytes than we should your solution.

**Comment by manuelsh** [comment]
Have a look to the following comparison:

![image](https://user-images.githubusercontent.com/11526217/79277350-eaacfe00-7ea9-11ea-84c1-f7f9828dcd06.png)

Re `board.tostring()` and `board.astype(int).tostring()` would yield the same result if we don't receive -0., but I am seeing them (on Python 3.6.8). I cloned it last week, maybe you introduced some changed already that prevents that.

**Comment by NMO13** [comment]
> Re board.tostring() and board.astype(int).tostring() would yield the same result if we don't receive -0., but I am seeing them (on Python 3.6.8). I cloned it last week, maybe you introduced some changed already that prevents that?

Sorry, I don't understand what you mean. I thought that the byte representation of array is the same regardless if these are +0 or -0.

![image](https://user-images.githubusercontent.com/3988444/79559602-4c39bc00-80a6-11ea-81a6-7f319f53c446.png)

Anyway I think we can easily resolve it by simply creating the board as int array:
![image](https://user-images.githubusercontent.com/3988444/79559878-c8cc9a80-80a6-11ea-8b43-3f314e7213f6.png)

What do you think?

**Comment by NMO13** [comment]
Another question: You showed that a.tostring() is slower than str(a).
So how can it be that 

>     def stringRepresentation(self, board):
         return board.astype(int).tostring()

is 100x faster than ```str(board)``` ?

**Comment by mikhail** [comment]
Keep in mind that this is used in a python dictionary to keep track of states. Dictionaries store keys with hash lookups, so perhaps the hashing is slower for the str() approach.

Additionally - you could change the entire architecture and instead of returning a representation of the entire board you could return the minimal needed data. For example: `np.argwhere(board != 0)` could do the trick here

**Comment by manuelsh** [comment]
> > Re board.tostring() and board.astype(int).tostring() would yield the same result if we don't receive -0., but I am seeing them (on Python 3.6.8). I cloned it last week, maybe you introduced some changed already that prevents that?
> 
> Sorry, I don't understand what you mean. I thought that the byte representation of array is the same regardless if these are +0 or -0.
> 
> ![image](https://user-images.githubusercontent.com/3988444/79559602-4c39bc00-80a6-11ea-81a6-7f319f53c446.png)
> 
> Anyway I think we can easily resolve it by simply creating the board as int array:
> ![image](https://user-images.githubusercontent.com/3988444/79559878-c8cc9a80-80a6-11ea-8b43-3f314e7213f6.png)
> 
> What do you think?

I think it's a good solution. Probably you are right on the string representation.



> Another question: You showed that a.tostring() is slower than str(a).
> So how can it be that
> 
> ```
> 
>      def stringRepresentation(self, board):
>          return board.astype(int).tostring()
> ```
> 
> is 100x faster than `str(board)` ?

Actually ´.tostring()´ is faster. Checkout the [units ](https://www.google.com/search?sxsrf=ALeKk03SU6MwQZeMnNJ277QeCeP8pOo9Wg%3A1587545529724&ei=uQWgXtflK46ca5y2vbgM&q=%CE%BCs+vs+ns&oq=%CE%BCs+vs+ns&gs_lcp=CgZwc3ktYWIQAzIECCMQJzoECAAQQzoCCAA6BggAEBYQHlCyMFi4P2CjQGgAcAB4AIABmAGIAY4IkgEDNC41mAEAoAECoAEBqgEHZ3dzLXdpeg&sclient=psy-ab&ved=0ahUKEwiXpvT60_voAhUOzhoKHRxbD8cQ4dUDCAw&uact=5) of my comparison. 

> Keep in mind that this is used in a python dictionary to keep track of states. Dictionaries store keys with hash lookups, so perhaps the hashing is slower for the str() approach.
> 
> Additionally - you could change the entire architecture and instead of returning a representation of the entire board you could return the minimal needed data. For example: `np.argwhere(board != 0)` could do the trick here

hey would be great to see an example and comparison

**Comment by NMO13** [comment]
Ah yes I didn't noticed the units. Its maybe a great idea of improving performance. I will try it out tomorrow.
BTW for you info, the -0 problem is already fixed in https://github.com/suragnair/alpha-zero-general/pull/174

**Comment by manuelsh** [comment]
nice!

**Comment by NMO13** [comment]
PR is open: https://github.com/suragnair/alpha-zero-general/pull/179
