### ISSUE TITLE
Checking valids in Arena.py

### ISSUE THREAD

**Issue by NMO13** [suragnair/alpha-zero-general#173]
The following code in Arena.py doesn't make sense for me:
```
 if valids[action]==0:
   print(action)
   assert valids[action] >0
```
The assert statement can only be False.

**Comment by goshawk22** [comment]
No, I also don't understand this? It seems it breaks the script if it gets an action of 0, but I don't understand why this is needed?

**Comment by goshawk22** [comment]
I am currently writing files for the game of Pawns (based off chess) and keep running into errors where the best action is 0. The code in Arena.py seems to stop the code to prevent these errors, but I'm not sure how to resolve them.

**Comment by rlronan** [comment]
valids is a binary array. 

```
 if valids[action]==0:          # this means the action you picked is invalid.
   print(action)                    # This is debugging information.
   assert valids[action] >0   # This is an assertion we know will fail, so that the code halts here 
                                          # with the explanation that valids[action] is not greater than 0 (i.e. invalid)
```

**Comment by astronasko** [comment]
Greetings, 
I get this error raised right now in pitting. Where could the problem be?
