### ISSUE TITLE
MCTS.py throws ZeroDivisionError: float division by zero

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#176]
Twice now I've encountered the following error:

```
  File "/Users/intj/git/alpha-zero-general/Coach.py", line 87, in learn
    iterationTrainExamples += self.executeEpisode()
  File "/Users/intj/git/alpha-zero-general/Coach.py", line 55, in executeEpisode
    pi = self.mcts.getActionProb(canonicalBoard, temp=temp)
  File "/Users/intj/git/alpha-zero-general/MCTS.py", line 48, in getActionProb
    probs = [x / counts_sum for x in counts]
  File "/Users/intj/git/alpha-zero-general/MCTS.py", line 48, in <listcomp>
    probs = [x / counts_sum for x in counts]
ZeroDivisionError: float division by zero
```

I can't reproduce the first case, but the second case is 100% reproducible when you set `numMCTSSims` to 1 in main.py

Can someone explain what this really means?

**Comment by NMO13** [comment]
The problem with ```numMCTSSims``` to 1 is that the tree is not expanding in this case. So MCTS only checks the root node. It doesn't make a lot of sense to check just the root node without expanding so this value should be prohibited.

**Comment by mikhail** [comment]
Oh, I may be misunderstanding what that value does. I thought it's the number of branches to explore. So a value of 1 would mean it would be a straight line rather than a tree. Is that wrong?

Also I'm not actually trying to train anything with this value, just using a low value for debugging purposes

**Comment by NMO13** [comment]
Every call to MCTS.search() finds exactly 1 new node. A node can be either an unexplored node or it can be an end state.

**Comment by mshanak** [comment]
I have the same problem even when I use the default settings in main.py
the error
```
 probs = [x/counts_sum for x in counts]
ZeroDivisionError: float division by zero
```
what is the `counts` array used for?

**Comment by mshanak** [comment]
Another question, what are the allowed values that we can use on the board cells? 
can we use `[0,1,-1,2,-2]`?
