### ISSUE TITLE
Returning -v from MCTS.search()

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#18]
https://github.com/suragnair/alpha-zero-general/blob/4599a881b9d5956b807b815793a224198e21e461/MCTS.py#L117

I've read your note about returning negative -v from the search(). Could you please provide some considerations about handling v/-v for a game where a player's move can be a chain of atomic moves. When we do search() for an atomic move we can't return -v because the player keeps moving and next player takes a turn after full chain of atomic moves is completed. Example of a game is Checkers (Draughts).

**Comment by suragnair** [comment]
https://github.com/suragnair/alpha-zero-general/blob/4599a881b9d5956b807b815793a224198e21e461/MCTS.py#L106

Would it suffice to add `v*=-nextPlayer` below this line?

**Comment by evg-tyurin** [comment]
Thank you for the idea. It seems simple and elegant. I will experiment to be sure it suffice.

I think the issue can be closed now and reopened in a case of necessity.

**Comment by evg-tyurin** [comment]
Most likely this helps. When I pit the same model trained with and without this trick against random player I get the following results (win/lost/draw).
88/11/1 - without the trick
94/4/2 - with the trick
