### ISSUE TITLE
Suggestion to text UI changes

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#180]
Hello!

I've forked the project for a personal use, but some of the changes I could send upstream. I've added `coloredlogs` to the infrastructure and replaced the progressbar with the standard `tqdm`. Any interest in a look like this?

![image](https://user-images.githubusercontent.com/3210918/80446629-2ee9c680-88cc-11ea-8c31-fa501065d028.png)

Other changes are not ones I can really push upstream (changes the pytorch, and Arena that are game specific)

- [x] Replace most print statements with log calls
- [x] Replace progressbar with tqdm

**Comment by suragnair** [comment]
Yes, this would be very nice indeed!

**Comment by suragnair** [comment]
Would also be great if you could remove the `pytorch_classification` directory and any code that depends on it (only the progress bar if I remember correctly). Thanks!
