### ISSUE TITLE
Max recursion depth

### ISSUE THREAD

**Issue by CallumDowling** [suragnair/alpha-zero-general#187]
I am experiencing the following recursion depth problem after specifying my game.

```Self Play:  32%|████████████████████████████████████████▎                                                                                     | 8/25 [02:37<05:35, 19.74s/it]
Traceback (most recent call last):
  File "/home/cal/Development/python/alpha-zero-general/MCTS.py", line 125, in search
    v = self.search(next_s)
  File "/home/cal/Development/python/alpha-zero-general/MCTS.py", line 125, in search
    v = self.search(next_s)
  File "/home/cal/Development/python/alpha-zero-general/MCTS.py", line 125, in search
    v = self.search(next_s)
  [Previous line repeated 994 more times]
  File "/home/cal/Development/python/alpha-zero-general/MCTS.py", line 122, in search
    next_s, next_player = self.game.getNextState(canonicalBoard, 1, a)
  File "/home/cal/Development/python/alpha-zero-general/expendibots/ExpendibotsGame.py", line 47, in getNextState
    b = board.getCopy()
  File "/home/cal/Development/python/alpha-zero-general/expendibots/ExpendibotsLogic.py", line 63, in getCopy
    b = Board()
RecursionError: maximum recursion depth exceeded
```
  

When first running self play, the program seems to get to a certain point then get stuck recursing. I have tried to limit the number of turns by incrementing the number of turns when get getNextState() is called, I have tried checking this value both in getWinState in my board class and setting valids[-1]=1 in getValidMoves. Because of the nature of the game, the action space is quite large, 40k valid actions, I don't think this is the problem though, any help would be appreciated.
[Expendibots.zip](https://github.com/suragnair/alpha-zero-general/files/4609825/Expendibots.zip)

**Comment by mikhail** [comment]
Add debug information about which state it's visiting and whether the state is valid etc. Every time I've run into this issue it was because the end condition for the game was incorrect.

Additionally look into the way you serialize your board representation. MCTS saves the game result in a dictionary based on this representation. If it's not unique then you may save "game not over" for a state that is actually game over

**Comment by CallumDowling** [comment]
Thanks! I believe I fixed it by changing the 2 draw conditions to having slightly different weight values.
