### ISSUE TITLE
keras nnet error: ValueError: not enough values to unpack (expected 3, got 0)

### ISSUE THREAD

**Issue by CallumDowling** [suragnair/alpha-zero-general#189]
I have had some success in getting my model to finish self play, but then crash with the titular error. 

I believe it is something to to with my getSymmetries(self, board, pi) function. It is not clear to me from documentation what this function needs to return to the nnet, as tafl and othello return quite different items, none of those functions work for my case.     

My game is an 8 by 8 board starting with 12 pieces -1/1 on certain squares, the pieces can stack up to any number and can move STACK_SIZE * NORTH|EAST|SOUTH|WEST squares per turn, possibly skipping over enemies but not on to enemy.

**Comment by goshawk22** [comment]
the getSymmetries function should return a list of all the symmetrical positions of the board and pi. For example, imagine a TicTacToe board. On the first move, someone might play X at 0,0 (the top left corner). This is the same as playing in any of the other corners, so the getSymmetries function would also return these boards and respective pi.
