### ISSUE TITLE
Some question about Gobang and pit.py

### ISSUE THREAD

**Issue by lebr0nli** [suragnair/alpha-zero-general#193]
First Question:
How to use the model in pit.py?
That seems only valid for Othello :(
How to edit it for Gobang?

----

Second Question:
Which model is valid and how can I use in pit.py?

in temp folder:
best.pth.tar.data-00000-of-00001
best.pth.tar.index
best.pth.tar.meta
or maybe all invalid and where's the valid output model?

----

Sorry for bad english and poor knowledge.
And thank you for yours patient :D

**Comment by mikhail** [comment]
There are pre trained models Othello and Tic tac toe. For others you'll have to generate your own models by running main.py

**Comment by lebr0nli** [comment]
Even I edit main.py for training gobang(Tensorflow)
My output model still is :

best.pth.tar.data-00000-of-00001
best.pth.tar.index
best.pth.tar.meta

not model.ckpt

Is this correct?


----

p.s:
I'm just a junior high school student,but I really want to learn something about python and deep learning.
Sorry for stupid quesition and pool knowledge about this.......
Thank you for yours patient.
