### ISSUE TITLE
What's the best way to continue?

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#196]
If I'd like to resume / re-run a training, should I configure main.py to read from checkpoint_best or from whatever the latest checkpoint is?

I'd like to automate some logic to have `python main.py --continue` and have it automatically read the correct training file and resume

**Comment by suragnair** [comment]
https://github.com/suragnair/alpha-zero-general/blob/5156c7fd1d2f3e5fefe732a4b2e0ffc5b272f819/main.py#L25-L26

Just change these?

**Comment by mikhail** [comment]
Right -- but 1) Change them to what? And 2) I have a wrapper script that runs main.py - so I want to be able to run it without having to edit the text file

**Comment by suragnair** [comment]
1) Usually the best, unless you have reason to believe that the latest model should be used
2) `argparse` would be useful. One catch is that NNet files have their own configs right now, which can even differ between libraries for the same, or even for two different architectures for the same library. E.g. [this](https://github.com/suragnair/alpha-zero-general/blob/master/othello/pytorch/NNet.py) vs [this](https://github.com/suragnair/alpha-zero-general/blob/master/othello/chainer/NNet.py)

**Comment by mikhail** [comment]
So if my `best` is from checkpoint 7 but then I also have 8 and 9 wouldn't those have extra data (the losing data?) to help it learn the negative cases as well as the positive ones?

**Comment by suragnair** [comment]
Yes, that is true as of the current implementation.
