### ISSUE TITLE
assert valids[action] > 0 AssertionError

### ISSUE THREAD

**Issue by astronasko** [suragnair/alpha-zero-general#203]
Greetings,
My agent completes first self-play and training series. In the pitting stage though, it returns ``Action 112 is not valid!`` and raises an error from ``assert valids[action] > 0``.

My ``is_legal_move()`` function correctly determines the move in question as invalid, but the MCTS tries it anyway. Why would the mask for valid moves fail in MCTS? What would be the source of error?

**Comment by mikhail** [comment]
Do you see errors during training such as `All valid moves were masked, doing a workaround.` ?
