### ISSUE TITLE
Where to add extra features to the model?

### ISSUE THREAD

**Issue by mikhail** [suragnair/alpha-zero-general#209]
I'd like to add extra "Features" to the ML model, but I don't want them to be part of the `board` that gets passed around. When would be the right time to add features? Would it be in the symmetries function?

For example, an additional feature to Chess or Go could be "count of black/white pieces on the board"

**Comment by goshawk22** [comment]
I think the get symmetries function is the best place to add them because this is right before it is added to the training dataset, assuming you want to feed the neural network this data?

**Comment by mikhail** [comment]
Yeah, I tinkered around with it but ended up doing it in `getBoard`. Doing it just for Symmetries was not sufficient because Arena / pitting would end up having a board without the extra feature data and evaluating the model would just be wrong. Seems like board and feature set is synonymous
