### ISSUE TITLE
othello tensorflow version bugs?

### ISSUE THREAD

**Issue by 1424667164** [suragnair/alpha-zero-general#21]
@suragnair 
```class OthelloNNet():
    def __init__(self, game, args):
        ......
        self.pi = Dense(s_fc2, self.action_size)
        self.prob = tf.nn.softmax(self.pi)
    def calculate_loss(self):
        ......
        self.loss_pi =  tf.losses.softmax_cross_entropy(self.target_pis, self.pi)
```
in this line
`self.loss_pi =  tf.losses.softmax_cross_entropy(self.target_pis, self.pi)`
is `self.pi` should be `self.prob`
??

**Comment by suragnair** [comment]
@SourKream 

Yes that's true. Equivalently, would it be correct make it `self.loss_pi =  tf.losses.softmax_cross_entropy_with_logits(self.target_pis, self.pi)`

**Comment by suragnair** [comment]
I fixed it with `self.loss_pi = tf.losses.softmax_cross_entropy_with_logits(self.target_pis, self.pi)` in the recent commit.

**Comment by brianprichardson** [comment]
Getting the error below with TF (but not with pytorch nor Keras):

(alpha-zero-general) C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general>python main.py
C:\alpha-zero-general\alpha-zero-general\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second
argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.d
type(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    nnet = nn(g)
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\NNet.py", line 29, in __i
nit__
    self.nnet = onnet(game, args)
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\OthelloNNet.py", line 40,
 in __init__
    self.calculate_loss()
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\OthelloNNet.py", line 48,
 in calculate_loss
    self.loss_pi =  tf.losses.softmax_cross_entropy_with_logits(self.target_pis, self.pi)
AttributeError: module 'tensorflow.python.ops.losses.losses' has no attribute 'softmax_cross_entropy_with_logits'
