### ISSUE TITLE
Regarding https://github.com/suragnair/alpha-zero-general/blob/master/othello/pytorch/NNet.py

### ISSUE THREAD

**Issue by paklau99988** [suragnair/alpha-zero-general#218]
Where can find code for calling train(examples) ? How to generate examples for training set? 

Thanks

**Comment by carlos-aguayo** [comment]
You should try running and debugging things locally...

"train(examples)" is being invoked here:
https://github.com/suragnair/alpha-zero-general/blob/master/Coach.py#L113

The training set is generated a few lines above, lines 84-106.
