### ISSUE TITLE
Bug in othello/pytorch/NNet.py

### ISSUE THREAD

**Issue by nimz** [suragnair/alpha-zero-general#22]
Dear authors of this repository,
There is a bug on line 150 of othello/pytorch/NNet.py. The line
````raise("No model in path {}".format(checkpoint))````
should be
````raise("No model in path {}".format(filepath))````

Also, in `pit.py` the filepath passed into `load_checkpoint` should be

````./pretrained_models/othello/pytorch/````

Thank you for looking into this!

**Comment by suragnair** [comment]
Thanks! I've pushed these changes. Have fun.
