### ISSUE TITLE
Masking Ps[s]*valids may give an array of zeros

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#23]
https://github.com/suragnair/alpha-zero-general/blob/a6077c9ee503686eaf5a7b0c513df2a2e33112c1/MCTS.py#L80

In this line we divide by sum of initial policy which were previously masked by valid moves (valids). 

I observe the cases when product of Ps[s]*valids is an array of zeros. So sum(Ps[s]) is also zero and in the given line we have numpy warning about "division by zero" after that all Ps[s][a] become NaN. Numpy doesn't raise an error so we go on and in the next visits of the state [s] we have best_act = -1 and then a = -1. Then we invoke 
next_s, next_player = self.game.getNextState(canonicalBoard, 1, a=-1)
which is conceptually illegal operation.

Such cases occur in the PIT phase of 1st iteration and then continue. When I debug a case I see that nn.predict() returns few nonzero values inside Ps[s] which don't match any value from valids and its product gives all zeros. On the next iterations a number of cases is gradually decreasing.

I think that occurences of those cases depend on random number generator because they are platform dependent. If I run the same program on different physical computers I may or may not observe those cases.

The question is, should we detect such cases and try to avoid NaNs in Ps[s]? If the case is detected we can for example make all valid moves equally probable, i.e.                 
self.Ps[s] = self.Ps[s] + valids
self.Ps[s] /= np.sum(self.Ps[s])

**Comment by suragnair** [comment]
In general all the `valid` vector should never be 0. For Othello with board size 6x6, the length of the `valid` vector is 6*6+1, where the extra 1 is for "Pass". Hence if no legal move is available, the "Pass" move will be available. By enforcing a similar scheme for all games, we shouldn't see the division error.

Can you think of any game for which the scheme might not work?

**Comment by evg-tyurin** [comment]
I didn't say that all valids were zero.
Subject is that the product of Ps[s]*valids gives an array of zeros when nonzero components of both arrays don't match.

Imagine the example with very little action space of 10:

P = np.array([0]*10)
valid = np.array([0]*10)

P[1] = 1
valid[2] = 1
print(P)

P = P*valid
print(P)

P /= np.sum(P)
division by zero

Such cases I observe in the game of Checkers.

**Comment by suragnair** [comment]
I see. This is unexpected since it should typically be highly unlikely that any single value in `valids` should be exactly equal to 0. It should usually be some very small but non-zero value, right?

**Comment by suragnair** [comment]
I believe it is related to #13. Are you on the latest version (or at least >= 4599a88)?

**Comment by evg-tyurin** [comment]
Maybe you mean that Ps[s] usually should have very small but non-zero values? valids are just flags and they're always exactly either 0 or 1.

Yes, I'm on the latest version and I'm aware of #13. As I see it may be another case and another reason for division by zero. As I've mentioned my cases start to occur at PIT phase of 1st iteration when the NN was already trained at least one time. That is while NN is clean (randomly initialized) it predicts Ps as "very small but non-zero values". When it was trained for the first time it sometimes returns unexpected values. I noticed that on later iterations NN may or may not return unexpected values depending on unknown conditions.

Is it possible that we can't return -v from MCTS.search() for asymmetric games?
I mean the total use of 'return -v' and not only the trick with v*=-next_player from #18?

**Comment by suragnair** [comment]
I apologise, I meant Ps[s] not valids.

Could you investigate the cases when Ps[s]*valids returns a 0 vector? It is possible there are mistake in the Game Logic.

I don’t understand. In which case would you not return v or -v? What would you return instead?

**Comment by evg-tyurin** [comment]
As I've investigated before, all `valids` (i.e. moves) were always calculated correctly for the state of the board. I was surprised that many components of Ps[s][a] were exactly zeros after nnet.predict(). Well, I'll make further investigation and then report here.

As for 'return -v', it was my thoughts and a kind of brainstorm. Most likely the algorithm is perfect.

**Comment by evg-tyurin** [comment]
I've noticed that the number of unexpected predictions occured during an iteration/training is strongly dependent of main.numMCTSSims. If I have numMCTSSims=25 I observe them 0-4 per iteration. If I have numMCTSSims=2 I observe them tens per iteration. "Unexpected predictions" have many components of Ps[s][a] were exactly zeros (see my previous post).

**Comment by suragnair** [comment]
That does make sense since having fewer MCTS simulations will leave some of the action counts as 0 since they were not explored. That would then train the neural network to make similar predictions and thus reinforce itself. Is it an issue when the number of simulations is higher (>=50)?

**Comment by evg-tyurin** [comment]
Strange results. I've set numMCTSSims=50 and have had tons of unexpected predictions on iteration 1 on Arena and then on Iteration 2 on both phases. Unfortunately, on Iter 3 program ran out of memory and has terminated. After some optimizations (free unused mcts, pmcts, nmcts variables in Coach.py), I ran the program again and had few unexpected predictions on iter 2 and 3 (10 or about) and none on iterations 4-6 (program still works).

**Comment by evg-tyurin** [comment]
After few experiments, I've recognized that the NN architecture inherited from sample implementation (of Othello) may be insufficient for the Checkers. It becomes especially obvious if we use input stack of image planes. When I extended the NN these unexpected predictions were eliminated entirely.

**Comment by evg-tyurin** [comment]
So, should the MCTS implementation detect the cases when the product of Ps[s]*valids is an array of zeros?

**Comment by suragnair** [comment]
Yes, it looks like we should implement this. Should we go ahead with your proposal 

> If the case is detected we can for example make all valid moves equally probable, i.e.
self.Ps[s] = self.Ps[s] + valids
self.Ps[s] /= np.sum(self.Ps[s])

**Comment by evg-tyurin** [comment]
Imho, this is just a workaround which hides probable problem with NN (like insufficiency) or training examples or smth else. I think we should immediately notify a developer who uses/extends the framework if such case appears.

As for workaround, yes we could implement the proposal but one should understand that we just ignore NN output and replace it with equally probable valid actions for the board position. If such cases appear on later iterations then they would appear not only in training thus making the model unusable (more or less).

**Comment by evg-tyurin** [comment]
If no other idea, I could commit the above proposal that would check if sum=0 and then report standard phrase to the STDOUT and reset Ps[s] to equally probable valid moves.

Standard phrase could be "All valid moves were masked, do workaround."

**Comment by emc2314** [comment]
IMHO, why not substitute division by subtraction in log scale?
Like:
```
Ps[s] = exp(log(Ps[s]) - log(max(Ps[s])))
Ps[s] /= sum(Ps[s])
```

**Comment by suragnair** [comment]
Sounds good. Please make a PR.

**Comment by evg-tyurin** [comment]
See  #39

**Comment by suragnair** [comment]
Thank you very much!
