### ISSUE TITLE
Framework For Chess In Keras Not Working

### ISSUE THREAD

**Issue by SwiftGodDev** [suragnair/alpha-zero-general#231]
Every time i run the main.py file it gives this error.

Traceback (most recent call last):
  File "main.py", line 7, in <module>
    from chess.keras.NNet import NNetWrapper as nn
  File "/content/drive/My Drive/alpha-zero-general/chess/keras/NNet.py", line 14, in <module>
    from .ChessNNet import ChessNNet as chessnet
  File "/content/drive/My Drive/alpha-zero-general/chess/keras/ChessNNet.py", line 9, in <module>
    from keras.backend.tensorflow_backend import set_session
ModuleNotFoundError: No module named 'keras.backend.tensorflow_backend'; 'keras.backend' is not a package

Heres the whole folder containing the code.

[chess.zip](https://github.com/suragnair/alpha-zero-general/files/5794923/chess.zip)
Just paste the link in URL bar it will get downloaded.

**Comment by goshawk22** [comment]
Could you reference the repository where this code came from?
I would imagine you need to change `from keras.backend.tensorflow_backend import set_session` to `from tensorflow.keras.backend.tensorflow_backend import set_session`

**Comment by SwiftGodDev** [comment]
I was wondering if we could write a RL algorithm for reconchess.
Please check these repos.

https://github.com/ceremonious/reconblindchess
https://github.com/devinjdangelo/recon-chess

**Comment by SwiftGodDev** [comment]
How can i use your chess framework in pytorch with this repo?

**Comment by goshawk22** [comment]
I don't think this issue is relevent for this repository - it's probably better to make an issue in the repo you are having issues with.
As for implementing ReconChess, you can look at the already implemented games for examples and adapt them for the rules of ReconChess. Look at [Game.py](https://github.com/suragnair/alpha-zero-general/blob/master/Game.py) for a guide.

**Comment by SwiftGodDev** [comment]
Thats the problem. I am new to coding.
