### ISSUE TITLE
TF change getting error (softmax_cross_entropy_with_logits)

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#25]
See #21 

(alpha-zero-general) C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general>python main.py
C:\alpha-zero-general\alpha-zero-general\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second
argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.d
type(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    nnet = nn(g)
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\NNet.py", line 29, in __i
nit__
    self.nnet = onnet(game, args)
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\OthelloNNet.py", line 40,
 in __init__
    self.calculate_loss()
  File "C:\alpha-zero-general\alpha-zero-general\Scripts\alpha-zero-general\othello\tensorflow\OthelloNNet.py", line 48,
 in calculate_loss
    self.loss_pi =  tf.losses.softmax_cross_entropy_with_logits(self.target_pis, self.pi)
AttributeError: module 'tensorflow.python.ops.losses.losses' has no attribute 'softmax_cross_entropy_with_logits'

**Comment by suragnair** [comment]
I apologize for the silly oversight on my part. I have changed it to `tf.losses.softmax_cross_entropy(self.target_pis, self.prob)`. Can you please test it and let me know if it works (I don't have the setup available right now).

**Comment by brianprichardson** [comment]
Seems ok.  It's working its way thru the first iteration, so past the softmax error.

**Comment by suragnair** [comment]
Would be great if you could post the log outputs of the first 10 or so iterations when done.

**Comment by brianprichardson** [comment]
Stopped with a recursion depth limit error.  temp dir has 2 checkpoints in it.  Unfortunately, I did not save the window.  This is on Win7 in a venv.  Will try TF again under Ubuntu later.
