### ISSUE TITLE
ask for permission to use your code in a book

### ISSUE THREAD

**Issue by ZhangHandi** [suragnair/alpha-zero-general#269]
Hi, thanks for making a such useful repo! I'm currently writing a book about deep learning and reinforcement learning, and I implemented your code for training AlphaZero agent to play connect4 game. I'm not sure if it's ok to publish this code in my book, though I have already made a reference. So, I want to ask your permission to use this code in my book, and if it's not ok, I will remove this part. Thanks for response.

**Comment by suragnair** [comment]
Yeah please go ahead!

**Comment by ZhangHandi** [comment]
Okay, thanks a lot!
