### ISSUE TITLE
Othello pytorch working well

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#28]
After commenting out the progress bar (NNet.py '# plot progress section' around line 95), pytorch version is running about 3-4 iterations per hour on GTX 1070, and only uses around 1.4GB memory, although 95% gpu utilization for the 10 epochs per iteration.  Up to 65 iterations so far with no visible issues.  Just wanted to share a positive post.  Thanks.

**Comment by suragnair** [comment]
Haha yes, I'd written it originally for PyTorch :).
