### ISSUE TITLE
Better model/weights

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#29]
Tried to upload, but too large.
After checkpoint 153.
Results pitted against pre-trained best (1580):

Arena.playGames |################################| (4097/2048) Eps Time: 3.473s | Total: 3:57:03 | ETA: 0:00:03
(1580, 2516, 0)

**Comment by suragnair** [comment]
Did you use a different architecture?

**Comment by brianprichardson** [comment]
No.  I just used the models from the Othello pytorch subdir.

Currently running an 8x8 game which is now up to checkpoint 39

**Comment by brianprichardson** [comment]
I tried to fork it (read that without write privs have to fork first and then submit a pull, I think) and upload a file, but it says 25MB is the limit.

**Comment by brianprichardson** [comment]
Nevermind.  I see for files >25MB the command line should be used.

**Comment by suragnair** [comment]
Details here: https://services.github.com/on-demand/github-cli/open-pull-request-github

**Comment by brianprichardson** [comment]
Please take a look at the pull request.
Thanks.

**Comment by suragnair** [comment]
Looks good. Thanks!
