### ISSUE TITLE
A fast, parallel and batched fork of this repo

### ISSUE THREAD

**Issue by Bobingstern** [suragnair/alpha-zero-general#290]
https://github.com/kevaday/alphazero-general
This repo has all of the improvements listed in the README although it only supports pytorch. There are some *tiny* bugs that I have been trying to sort out but if anyone wants a general AlphaZero implementation that works for tougher envs here it is. It's also based off of this one!  https://github.com/Bobingstern/AlphaZero-Connect-4 is an example I made using tensorflow.js training using it. It supports FPU reduction, model gating, dirichlet noise and cython for even faster speed. Some envs are a little broken though but I will send a PR eventually with the fixed ones and more.

**Comment by suragnair** [comment]
Thanks for letting me know! Added to README.
