### ISSUE TITLE
Is pytorch necessary?

### ISSUE THREAD

**Issue by sharpwood** [suragnair/alpha-zero-general#3]
I have changed pytorch to keras in main.py .
But...

 \pytorch_classification\utils\misc.py", line 12, in <module>
    import torch.nn as nn
ModuleNotFoundError: No module named 'torch'

**Comment by suragnair** [comment]
Thanks for pointing that out. Could you check the latest commit and let me know if it works for you?

**Comment by sharpwood** [comment]
It works now . Thanks.
