### ISSUE TITLE
Actionspace 1 to many

### ISSUE THREAD

**Issue by Pieterjan-byte** [suragnair/alpha-zero-general#305]
What is the reason that the action space is enlarged by one? Doesn't this lead to wrong models?

![Schermafbeelding 2023-05-12 194708](https://github.com/suragnair/alpha-zero-general/assets/73665439/42af6415-da7c-4349-a972-867503910be5)

**Comment by zimpzon** [comment]
It is for no move. Allowed in some games, not in others.

**Comment by Pieterjan-byte** [comment]
How do I handle this in a game that does not allow it?

**Comment by zimpzon** [comment]
You just leave out that last element. I can't help you more than that, I'm having some trouble implementing my own custom game. Don't expect it to be easy ;)
