### ISSUE TITLE
Separate Policy and Value Networks

### ISSUE THREAD

**Issue by brianprichardson** [suragnair/alpha-zero-general#33]
The AlphaGo Zero paper mentions a difference from the prior AlphaGo approach is that the Policy and Value networks are combined.  Could you please explain a bit about this and the method chosen for alpha-zero-general?
Thanks.

**Comment by suragnair** [comment]
What this is means is that the same network has two outputs- a policy (distribution over actions) and a scalar value. Previously in AlphaGo, they had trained two separate networks- one for policy and one for value. However, for AlphaGo Zero they used a combined network that enabled more efficient use of training data.

This repository (alpha-zero-general) uses a single network which outputs the policy and the value. 

https://github.com/suragnair/alpha-zero-general/blob/2a3780796d671c565f5d3d9a1e979c4f012bb041/othello/pytorch/OthelloNNet.py#L56

**Comment by brianprichardson** [comment]
Very helpful.  Thanks.
