### ISSUE TITLE
batch_size

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#37]
In the paper, they said that they optimized neural networks using 64 GPU workers and the batch size was "32 per worker, for a total mini-batch size of 2048".

I'm a bit confused how do their GPU workers could correlate to my single GPU which internally processes the batches in a multi-threaded way. So, if I use single GPU should I set batch_size=32 or batch_size=2048 to be more close to the original algorithm and methods?

**Comment by suragnair** [comment]
I believe 2048 would be more close. I assume their GPUs would communicate with each other to sync.

**Comment by evg-tyurin** [comment]
Thanks! And why do you use batch_size=64? Is this related to a relatively small number of examples being gained per iteration?

**Comment by suragnair** [comment]
Yes, that and pretty much everything else is on a much smaller scale. For e.g. they use 16000 MCTS simulations per move and 25000 games per iteration (we use ~50 and 100 respectively).

**Comment by evg-tyurin** [comment]
*1600 MCTS simulations

**Comment by suragnair** [comment]
That's correct, my bad!
