### ISSUE TITLE
Reward calculation in Self-Play is probably Othello specific

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#38]
https://github.com/suragnair/alpha-zero-general/blob/56aad5e12840dbf77aeab760db3c171bb9235aa9/Coach.py#L62

This is probably Othello specific while works good if black make the first move.

What could I do if I implement a game with white make the first move?

Assume white won and we calculate reward for the first move:
`reward = r * ( (-1) ** (x[1] != curPlayer) )`

r=1 as white won
curPlayer=-1 as black to move (white made the last move and won the game)
x[1]=1 as assume this is the first move

reward = 1* ( -1 ** 1) = -1  -  must be +1

**Comment by suragnair** [comment]
This is not Othello specific. `self.curPlayer` here is the player at the final step in the game and r is the reward (+1 if the player wins, else -1). So reward is assigned for all previous steps by comparing whether the player for that step is the same as curPlayer.

**Comment by suragnair** [comment]
In the example you described, `cur_player` would be 1 and not -1, since when white won the game, we went to line 62 and stopped the episode.

**Comment by evg-tyurin** [comment]
https://github.com/suragnair/alpha-zero-general/blob/f67e87ec2c30548e79d2274ec83f9946cf625066/othello/OthelloGame.py#L35

Not at all. After getNextState() and the above line curPlayer is already switched to -1.

**Comment by suragnair** [comment]
Let's say curPlayer is 1 before this line is executed

https://github.com/suragnair/alpha-zero-general/blob/56aad5e12840dbf77aeab760db3c171bb9235aa9/Coach.py#L57

Then player 1 plays the game and wins it. Then after execution curPlayer becomes -1 (you are correct).

https://github.com/suragnair/alpha-zero-general/blob/56aad5e12840dbf77aeab760db3c171bb9235aa9/Coach.py#L59

But in this line the reward is with respect to the curPlayer, which is -1. `So r= -1`

**Comment by evg-tyurin** [comment]
You're right. I apologize for the noise.
