### ISSUE TITLE
Can getGameEnded method support the draw?

### ISSUE THREAD

**Issue by sharpwood** [suragnair/alpha-zero-general#4]
Can getGameEnded method support the draw?

**Comment by suragnair** [comment]
Not by default- it returns 1 or -1 depending on who wins, else 0 if the game hasn't ended. To incorporate draws, you'll can make getGameEnded return True/False and add another method getGameReward that returns the reward.

**Comment by suragnair** [comment]
Another hacky method would be to have getGameEnded return a very small value (like 1e-8).
