### ISSUE TITLE
Bug in getGameEnded() / GoBang

### ISSUE THREAD

**Issue by ikv33** [suragnair/alpha-zero-general#40]
There are two 5 in row results. Black from 6,0 to 2,4 and White from 1,0 to 5,4. Black had it first, but White won.

Game over: Turn  65 Result  1
0 |1 |2 |3 |4 |5 |6 |7 |8 |9 |
-----------------------
0 |W W W W b W b W b W |
1 |W W W W b W b W b W |
2 |b W b W b W b W b - |
3 |W b W b W - - - - - |
4 |b W b W - - - - - - |
5 |W b W b W - - - - - |
6 |b W b - - - b - - - |
7 |W b W - - - - - - - |
8 |b W b W b - - - - - |
9 |b b b W b W b b b b |
   -----------------------

**Comment by suragnair** [comment]
@1424667164

**Comment by suragnair** [comment]
@ikv33 Looks like it has been fixed, please reopen if the issue persists. Thanks!
