### ISSUE TITLE
where is the file tictactoe_main.py?

### ISSUE THREAD

**Issue by arfan** [suragnair/alpha-zero-general#42]
where is the file tictactoe_main.py? 

thank you

**Comment by evg-tyurin** [comment]
https://github.com/evg-tyurin/alpha-zero-general/tree/master/tictactoe

**Comment by suragnair** [comment]
I removed it since it was redundant. You simply need to replace Othello by TicTacToe in the imports for main.py here https://github.com/suragnair/alpha-zero-general/blob/master/main.py .
