### ISSUE TITLE
possible bug in MCTS.py ?

### ISSUE THREAD

**Issue by jih332** [suragnair/alpha-zero-general#43]
Hi, I've read your code, and I found that in MCTS.py line 106:
`u = self.args.cpuct*self.Ps[s][a]*math.sqrt(self.Ns[s])`
if we're at a node with no child node, then `self.Ns[s]` would be 0. Hence, the `u` for all the `(s, a)` would be 0. It will choose the first valid action as the best one. `self.Ns[s]` will not be updated to 1 before the `v` of its first child node is returned.
shouldn't it be 
`u = self.args.cpuct*self.Ps[s][a]*math.sqrt(self.Ns[s]+1)` ?

**Comment by suragnair** [comment]
That seems correct. I believe it would be more appropriate to make it

`u = self.args.cpuct*self.Ps[s][a]*math.sqrt(self.Ns[s]+EPS)`

where `EPS` is a small value (say 1e-8). What do you think?

**Comment by jih332** [comment]
you're right. that makes sense.
