### ISSUE TITLE
Picking the best child in the MCTS in event of a tie

### ISSUE THREAD

**Issue by Blackmoor** [suragnair/alpha-zero-general#48]
A slight improvement to the MCTS.search code would cope with multiple actions having the same confidence.

line 99 becomes:
best_act = []

lines 109-111 become
if u > cur_best:
  best = u
  best_act = [ a ]
elif u == cur_best:
  best_act.append(a)

line 113:
a = random.choice(best_act)

**Comment by suragnair** [comment]
Since the `u` values in questions are floats that are predicted by the neural network plus an additional term, such a case of an exact match would be very rare. It may not be worthwhile to make this edit in the interest of readability. Thanks for the suggestion!

**Comment by evg-tyurin** [comment]
In practice, it works. 

If you implement mentioned improvement as well as rewrite 
https://github.com/suragnair/alpha-zero-general/blob/f7fdd37fa43293f989e2c8f2ac101cfa4e79dc90/MCTS.py#L38
to pick one of the best moves then you could fix #24 because the games would not be identical.

**Comment by suragnair** [comment]
@evg-tyurin the suggestions sounds good. I'm not sure if `elif u == cur_best:` would happen very frequently.
