### ISSUE TITLE
temp in MCTS.getActionProb()

### ISSUE THREAD

**Issue by jih332** [suragnair/alpha-zero-general#49]
Hi, I noticed that in MCTS.py line 43:
`counts = [x**(1./temp) for x in counts]`
However, temp passed in here only alternate between 0 and 1. The only calculation of `temp` is at Coach.py line 49:
`temp = int(episodeStep < self.args.tempThreshold)`
which makes `x**(1./temp)` meaningless since temp is always 1. I guess your original intention was to flatten the distribution a little bit to allow more exploration?
Please correct me if I missed something. Thanks!

**Comment by suragnair** [comment]
That's correct- it just makes it more explicit and general. It also accommodates more complex schemes for temperature if one chooses to do so.

**Comment by jih332** [comment]
got it. Thanks!
