### ISSUE TITLE
Go game implementation?

### ISSUE THREAD

**Issue by arisliang** [suragnair/alpha-zero-general#50]
Since the alpha zero paper uses Go as the example, it seems natural to provide a Go implementation as well. Or perhaps is there any pointer that you can give to implement it?

**Comment by suragnair** [comment]
It should not be too difficult to write an implementation for Go- it's possible that one of the forks of this repository has a version. Unfortunately, I don't know much about the rules, but it should be easy to adapt them to the framework of this repository.

**Comment by alreadydone** [comment]
Leela Zero (for Go) didn't start out "general", but the code has been ported to chess and used in the LCZero project.
