### ISSUE TITLE
How To Install and use?

### ISSUE THREAD

**Issue by putuoka** [suragnair/alpha-zero-general#52]
Could you please write a step how to install and use this to play Othello or tic tac toe?

Thanks in advance

**Comment by suragnair** [comment]
If you download the pretrained models, simply running `python pit.py` should allow you to play against the model. Let me know if that works.

**Comment by putuoka** [comment]
@suragnair if i use this step can this work or not

```
1. git clone https://github.com/suragnair/alpha-zero-general.git
2. python pit.py
```

sorry if the question is very noob

**Comment by suragnair** [comment]
Yes, assuming you have PyTorch installed, should work.

**Comment by putuoka** [comment]
@suragnair awesome. Thank you so much

**Comment by woctezuma** [comment]
I bump this thread, because the project would benefit from a `requirements.txt` file, so that one could install all the required packages with a single command:

`pip install -r requirements.txt`

I will try to see if all the dependencies are installed with pytorch.

**Comment by suragnair** [comment]
I am under the assumption that simply installing pytorch should be enough. Is that wrong?

**Comment by woctezuma** [comment]
I cannot confirm, because my hardware is too old for installing pytorch.

However, then you could still write somewhere that the requirement is just pytorch. Otherwise, it is a bit confusing to open the project and see numpy missing, and ignore how many additional packages are required.
