### ISSUE TITLE
Implement Connect4 player

### ISSUE THREAD

**Issue by rodo-r2r** [suragnair/alpha-zero-general#53]
I've been working on adding a Connect4 player on my fork and thought I should open an issue here to track progress. I assume you'd like to merge this in when it's done?

https://github.com/rodneyodonnell/alpha-zero-general/commits/connect4

Currently I've been training it for ~20 iterations (numEps=100, numMCTSSims=200) and it doesn't seem to play significantly better than it did after a single iteration. Still trying to understand why.

The model I've trained easily defeats random even with minimal MCTS steps in the arena, and can beat humans (me) with a moderate MCTS.

**Comment by rodneyodonnell** [comment]
Oops, was logged in as my work github account.
Not sure there is any way to edit a post's author.

**Comment by suragnair** [comment]
Sounds great! Would be great if you can make a pull request with a self-contained folder and README (like https://github.com/suragnair/alpha-zero-general/tree/master/tictactoe).

**Comment by rodneyodonnell** [comment]
Sure, it should be set up like that already.

I still haven't been able to train a model I'm happy with, did you want me to make a pull request anyway without a model?

**Comment by suragnair** [comment]
You could make a pull request without the model now, and another one later when you're satisfied with the model :).
