### ISSUE TITLE
parallelization of MCTS ?!

### ISSUE THREAD

**Issue by aldazero** [suragnair/alpha-zero-general#55]
Thank you very much for providing this useful repository. I have a question regarding with parallelization of MCTS simulations. In the paper they have mentioned that they have used several threads for doing MCTS simulations in parallel. But I can't see any source of randomness in the Monte Carlo simulations in each step. Do you have any idea? Sorry if my question is stupid!  I am new in this field. 

I would also be grateful if you could let me know how can one parallelize collecting data and training networks, cause it seems that this is the method that they implemented in their work. 

Thank you very much!

**Comment by suragnair** [comment]
Hi, perfectly legitimate question! I had the same observation about the MCTS simulations- it doesn't look like it's possible to parallelize a single simulation. My guess is that they share a GPU between multiple games being generated and then pool the queries from each simulation to make a GPU batch.

Data collection can be parallelized by having each CPU self-play one or a few games. The network training can also happen as a parallel thread that can replace the "global" neural network in case the new one beats the old one.

I should add my system skills are still pretty nascent and my terminology may be off-point.

**Comment by evg-tyurin** [comment]
@aldazero look at https://github.com/evg-tyurin/alpha-nagibator

There are parallel self-play and evaluation phases.

**Comment by sharpobject** [comment]
You can read about how to parallelize a tree search from a particular position at http://www.moderndescartes.com/essays/agz/ under "Virtual losses"
