### ISSUE TITLE
Channel Size hardcoded to 512?

### ISSUE THREAD

**Issue by SJCaldwell** [suragnair/alpha-zero-general#58]
Love your project, and I'm working on adding code to accommodate playing Mini-Shogi. 

I've determined the number of channels will need to be around 250 (to keep an 8 step history of every kind of piece, etc). However, I'm noticing that in the current default args there's:

```python
args = dotdict({
    'lr': 0.001,
    'dropout': 0.3,
    'epochs': 10,
    'batch_size': 64,
    'num_channels': 512,
})
```

Which is used in OthelloNNet.py as follows

```python
h_conv1 = Relu(BatchNormalization(self.conv2d(x_image, args.num_channels, 'same'), axis=3, training=self.isTraining))     # batch_size  x board_x x board_y x num_channels
```
But it seems like this should be 1, seeing as the Othello board is represented entirely by a single matrix of -1s, 0s, and 1s. Can you explain how 512 channels was chosen and why? I'm sure it's something straightforward, but I haven't been able to figure it out. Any help would be very much appreciated!

**Comment by suragnair** [comment]
Hi, thanks!

The tensorflow conv2d takes the output number of channels (I suppose it figures out the input itself). Check it out here: https://www.tensorflow.org/api_docs/python/tf/layers/conv2d

We define self.conv2d as follows:
https://github.com/suragnair/alpha-zero-general/blob/065d95cc7e35dfa6baa210e558ee05d8c6757a2a/othello/tensorflow/OthelloNNet.py#L43
