### ISSUE TITLE
Error raised due to non existing file

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#6]
https://github.com/suragnair/alpha-zero-general/blob/263eccb2de3ca5eae7d5615e8b5b7d13b481b569/othello/keras/NNet.py#L69

When I start learning the NN the error raised due to file '....meta' is not created by save_checkpoint but is checked by load_checkpoint. Error raised in Coach after collecting trainexamples and before training new network. 

Windows 10, Python 3.6.

**Comment by suragnair** [comment]
Should be `os.path.exists(filepath)`. Fixed.
