### ISSUE TITLE
GPU utilization

### ISSUE THREAD

**Issue by JernejHabjan** [suragnair/alpha-zero-general#60]
Hi, first i want to thank you for this awesome repo.

I have a question about gpu utilization, because on my computer, when building model using OthelloGame and pytorch\OthelloNNNet, gpu utilization doesn't surpass the 2% mark, and I have gtx 1070 graphics card.

![image](https://user-images.githubusercontent.com/21958321/39961089-23e6329a-562f-11e8-9aab-55b1721e7443.png)

Is there something going on that I don't know about, or is this NN model just not deep enough to use all gpu power.

I've tried increasing batch size and changing 'cuda' flag to True, but that doesn't seem to help.

Also one more question. Is gpu also used with tensorflow and keras models? With these NN models, I am only getting CPU load and not gpu.

**Comment by suragnair** [comment]
Yep, that's correct! It's a pretty small neural network for a 6x6 grid. Increasing batch size should increase the GPU utilization, though.

Yes, it works with TensorFlow and Keras. You just need to configure your TensorFlow or Keras to use GPU by default (e.g. you need to be using tensorflow-gpu).

**Comment by JernejHabjan** [comment]
Thanks for pointing out tensorflow-gpu. Now both Keras and TensorFlow are using GPU - 40% at that!

Increasing batch size in any of games NNet.py files for Keras, TensorFlow or PyTorch, doesn't increase gpu utilization, but it stays the same.
```python
args = dotdict({
    'lr': 0.001,
    'dropout': 0.3,
    'epochs': 10,
    'batch_size': 4096,
    'cuda': True,
    'num_channels': 512,
})
```
PyTorch NNet still doesn't surpass 2% mark even if updating batch_size

**Comment by suragnair** [comment]
Is this the GPU utilization when the neural networks are being trained? GPU utilization would be low during the self-play stage since MCTS only sends one example at a time.

https://github.com/suragnair/alpha-zero-general/blob/065d95cc7e35dfa6baa210e558ee05d8c6757a2a/Coach.py#L117

**Comment by JernejHabjan** [comment]
Yes, its during Self play stage.
I don't understand why PyTorches' utilization is so much lower than the ones from TensorFlow or Keras.
Thanks for quick reply.

**Comment by suragnair** [comment]
2% sounds more legitimate to me during self-play since we are only performing inference on one sample at a time. Unsure why TensorFlow/Keras have more GPU usage- will have to dig deeper. Let me know if you find out!

**Comment by JernejHabjan** [comment]
Ok thanks for everything and I will report if I find out anything.
Closing issue.
