### ISSUE TITLE
connect4 symmetries

### ISSUE THREAD

**Issue by pjcorp** [suragnair/alpha-zero-general#69]
Hi,
I've been playing with this code for some days, very instructive, thank you!
I'm wondering, in getSymmetries for connect4, shouldn't the vector pi also be reversed along with the board?
Thanks

**Comment by suragnair** [comment]
Yeah, looks like it should be.

@rodneyodonnell

**Comment by rodneyodonnell** [comment]
Yep, definitely a bug. Thanks for catching this!
I'll put together a fix.

This could also explain why I wasn't seeing any real improvement by including the nnet.
I'll also kick off another training run to see how things look.
