### ISSUE TITLE
"best player from previous iterations" should not exist in AlphaZero implementation?

### ISSUE THREAD

**Issue by justindujardin** [suragnair/alpha-zero-general#74]
Thanks for the really cool project! I was reading over the AlphaZero paper and it seems like they dropped the self-play evaluation and best player selection in favor of continuous updates to the latest model when they moved from AlphaGo Zero to AlphaZero.

> In AlphaGo Zero, self-play games were generated by the best player from all previous iterations.
After each iteration of training, the performance of the new player was measured against
the best player; if it won by a margin of 55% then it replaced the best player and self-play games
were subsequently generated by this new player. In contrast, AlphaZero simply maintains a single
neural network that is updated continually, rather than waiting for an iteration to complete. Self-play games are generated by using the latest parameters for this neural network, omitting
the evaluation step and the selection of best player.

It seems like they did not offer a lot of detail about the way they continuously update the model. I'm guessing they used some distributed model with Tensorflow that takes care of coordinating the model updates.

Are there any plans to update this repo with a continuously updated model like in AlphaZero?

**Comment by suragnair** [comment]
You can simply comment out the pit phase from Coach.py and I believe that will be equivalent to continuously updating a single model.

**Comment by justindujardin** [comment]
Thanks, I've been using this approach for a few days now and it seems to work as expected. 👍 

I was curious about the part `rather than waiting for an iteration to complete` which seemed like they were continuously updating during self-play.
