### ISSUE TITLE
installation requirements or description to install and run this from scratch?

### ISSUE THREAD

**Issue by Mr-Mondragon** [suragnair/alpha-zero-general#75]
This project looks very promising and I'd love to try and experiment with this.

I'm rather inexperienced so maybe this is a really retarded question, but are there any installation steps I have to take to start from scratch (in my case for macOS) in order to run this?

When I clone this repos and run `python main.py` I am getting:

> Traceback (most recent call last):
>   File "main.py", line 3, in <module>
>     from othello.pytorch.NNet import NNetWrapper as nn
>   File "./othello/pytorch/NNet.py", line 15, in <module>
>     import torch
> ImportError: No module named torch

I assume I am supposed to install something called 'torch', although I don't know how or where, and I reckon there will be a lot of other libraries or depencies required as well.

Is there an easy way to run this project from a completely new i.e. 'blank slate' development environment?

**Comment by Mr-Mondragon** [comment]
(addition, in case it's relevant: I'm on macOS 10.13.4 and using python 2.7.15 and also have python 3.7.0 installed)

**Comment by suragnair** [comment]
PyTorch (torch) is one of the deep learning framework that this repo supports. You can find installation instructions here https://pytorch.org. The reason we don't offer a requirements file is because it supports multiple deep learning frameworks (PyTorch, TensorFlow, Keras) and you only need one. Good luck!
