### ISSUE TITLE
How to *not* use getCanonicalForm

### ISSUE THREAD

**Issue by tanmayb123** [suragnair/alpha-zero-general#83]
For my specific implementation of a game, `getCanonicalForm` is inapplicable (you can't just swap the players). How can I prevent the application from using it?

**Comment by suragnair** [comment]
You can simple return the board itself so long as it has information on which player is currently playing. For example you can have a channel that is all 1s if black is playing and all 0s if white is playing.

**Comment by tanmayb123** [comment]
Perfect, thanks!
