### ISSUE TITLE
TicTacToe 40x40?

### ISSUE THREAD

**Issue by aletote** [suragnair/alpha-zero-general#84]
I was thinking on implement this on my own game but the board will be 40x40. As a test I tried to train a tictactoe 40x40 but it's taking ages to even complete a single game.
Any ideas what I should do?

**Comment by JernejHabjan** [comment]
To speed up game iteration, you can reduce number of mcts simulations, number of eposides to play and number of iterations. Make sure you are using gpu for learning(keras, tf, pytorch). You can also reduce num of epochs.
But any of these reductions might slow learning down significantly, so use caution. But at these board dimensions, i dont think its smart to reduce learning time
