### ISSUE TITLE
Othello's "Resnet" lacks initial convolutional block (by the paper)

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#85]
Resnet merged from #81 lacks initial convolutional block before the residual tower (by the paper).

**Comment by gigayaya** [comment]
Add these code after line 69:
https://github.com/suragnair/alpha-zero-general/blob/1bc95ea3a1a64d062d8bdd50dd756767c2862cf5/othello/tensorflow/OthelloNNet.py#L69

```
x_image = tf.layers.conv2d(x_image, args.num_channels, kernel_size=(3, 3), strides=(1, 1),name='conv',padding='same',use_bias=False)
x_image = tf.layers.batch_normalization(x_image, axis=1, name='conv_bn', training=self.isTraining)
x_image = tf.nn.relu(x_image)
```
