### ISSUE TITLE
Pretrained model tar file is probably pytorch-specific

### ISSUE THREAD

**Issue by evg-tyurin** [suragnair/alpha-zero-general#9]
https://github.com/suragnair/alpha-zero-general/blob/e8a1f4171fbf6c81b264acba63cbf3f24dcfa7e2/pit.py#L24

Mentioned tar file is incompatible with keras so I'd propose either to make subdir(s) in pretrained_models or add suffix pytorch/keras to the model tar files.

**Comment by suragnair** [comment]
It is indeed, as was mentioned in the README. Refactored.
