### ISSUE TITLE
Othello 40x40 FC layers question

### ISSUE THREAD

**Issue by aletote** [suragnair/alpha-zero-general#91]
I'm running out of memory when trying to train an Othello 40x40. If I lower the the neurons on the fully connected layers to 128 and 64 I can do it. But that's not the ideal case, I want those 1024 neurons, what I don't understand is why I can't get them when I can when using conv neural networks like VGG16 with more than 40x40 pixels?

**Comment by alreadydone** [comment]
I guess you don't need 40x40 output when processing images?

**Comment by aletote** [comment]
self.fc4 = nn.Linear(64, 1)
Output is 1, like when processing images.

**Comment by alreadydone** [comment]
self.fc3 = nn.Linear(512, self.action_size)
I believe action_size is 40x40 in your case. fc3 is for policy and fc4 is for value, apparently.
fc3 doesn't seem to be the largest one though:
self.fc1 = nn.Linear(args.num_channels*(self.board_x-4)*(self.board_y-4), 1024)
It seems num_channels is 512 so you get a whopping 512x36x36x1024 here.
I think this doesn't agree with Alpha(Go)Zero, though. Leela Zero follows the AlphaGo Zero paper pretty faithfully and has a (19x19)x2x(19x19+1) fc layer for policy head and 19x19x256 and 256x1 fc layers for value head. (Note that there is "a convolution of 2 filters of kernel size 1×1 with stride 1" before fc in the policy head, so the number of channels is reduced to 2 (as in (19x19)x2x(19x19+1)).)

**Comment by JernejHabjan** [comment]
Where exactly are you running out of memory.
In my example, I was receiving MemoryError when trying to save train examples using Pickle.
By disabling that, I wasn't receiving errors any more.
