### ISSUE TITLE
Playing the game after training it

### ISSUE THREAD

**Issue by javismiles** [suragnair/alpha-zero-general#92]
Good day, 
I just ran main.py to do the training,  using Tensorflow, (so i changed pytorch to tensorflow in main.py).
So the training ended. Now, questions:

a) Where is the model created exactly stored? I notice that in /temp folder a lot of files have  been created,  is the  model one of them, which one?

b) If now I want to use pit.py to play against the machine with that model what do I have to do? right now I get errors when running pit.py maybe because I´m not refering the model created by tensorflow, how and where do I reference it, where is it stored after  the training and what do I change  in pit.py to reference it? Im using tensorflow, no pytorch, thank u very much

Traceback (most recent call last):
  File "pit.py", line 24, in <module>
    n1.load_checkpoint('./pretrained_models/othello/pytorch/','6x100x25_best.pth.tar')
  File "/home/myuser/alphazero/alpha-zero-general/othello/tensorflow/NNet.py", line 120, in load_checkpoint
    raise("No model in path {}".format(filepath))
TypeError: exceptions must derive from BaseException

**Comment by javismiles** [comment]
So if I edit pit.py and use this:

n1.load_checkpoint('./temp','best.pth.tar')

referencing the latest file created by my recently completed test training, 
then pit.py executes, but I see just two turns happen and nothing else

how do you play against it?

thank u

**Comment by suragnair** [comment]
That checkout seems correct. Is this for Othello?
