### ISSUE TITLE
Multi gpu model, low GPU utilization

### ISSUE THREAD

**Issue by tensorgpu** [suragnair/alpha-zero-general#93]
Training using GPU only utilize 1% of my GPU, anybody able to enhance it?

Maybe using keras.utils, multi_gpu_model?

**Comment by brianprichardson** [comment]
If on Windows, use MSI Afterburner or GPU-Z to properly see GPU usage.

Otherwise, more info needed.

**Comment by tensorgpu** [comment]
Thank you, now I see 36% utilization.
