### ISSUE TITLE
Use Unity to play with AI 

### ISSUE THREAD

**Issue by tensorgpu** [suragnair/alpha-zero-general#94]
Anybody free to create an Unity project so we can play with the Tensorflow trained result, like below:

SSSxCCC/AlphaZero-In-Unity : https://github.com/SSSxCCC/AlphaZero-In-Unity

**Comment by JernejHabjan** [comment]
Hey

I created RTS game in Ue4 (welp its not unity) and connected it to python module with ue4-tensorflow plugin to pull recomended actions from it.
Its still in its early days but if somebody is interested, i can explain it better so you can implement your game in ue4 and connect it with Alpha Zero module.

https://github.com/JernejHabjan/TrumpDefense2020
