### ISSUE TITLE
change the game

### ISSUE THREAD

**Issue by chengsu99** [suragnair/alpha-zero-general#99]

**Comment by chengsu99** [comment]
Hello. Can I use it to make prediction like tensflow？

**Comment by suragnair** [comment]
Hi. Can you please explain the question in more detail?

**Comment by suragnair** [comment]
Will calling this function solve your problem?

https://github.com/suragnair/alpha-zero-general/blob/b9f93486f31e1206aaa557b85292d16e2792dab2/NeuralNet.py#L27

**Comment by chengsu99** [comment]
let mehave a try. thank you.
